/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// mol2d-viewer/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RDKitPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// mol2d-viewer/settings.ts
var DEFAULT_SETTINGS = {
  bondColor: "#ffffff",
  containerWidth: "fit-content",
  reactionContainerWidth: "100%",
  imageWidth: "300px",
  imageHeight: "auto",
  showDetails: true,
  detailsPosition: "bottom",
  useLocalResourceOnly: true,
  theme: "standard",
  borderColor: "#cccccc",
  borderWidth: "1px",
  backgroundColor: "transparent",
  imageBackgroundColor: "transparent",
  legendColor: "var(--text-normal)",
  generate3D: false
};

// mol2d-viewer/settingTab.ts
var import_obsidian = require("obsidian");
var RDKitSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "RDKit Render Settings" });
    new import_obsidian.Setting(containerEl).setName("Container Layout Width").setDesc("Use 'fit-content' or fixed px/% value. / \u8FB9\u6846\u5305\u88F9\u5BBD\u5EA6\u8BBE\u7F6E\u3002").addText((t) => t.setValue(this.plugin.settings.containerWidth).onChange(async (v) => {
      this.plugin.settings.containerWidth = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Image Width / \u56FE\u7247\u5BBD\u5EA6").addText((t) => t.setValue(this.plugin.settings.imageWidth).onChange(async (v) => {
      this.plugin.settings.imageWidth = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Title (Legend) Color / \u6807\u9898\u6587\u5B57\u989C\u8272").setDesc("Color for the legend text. / \u72EC\u7ACB\u8BBE\u7F6E\u56FE\u7247\u4E0B\u65B9\u6807\u9898\u6587\u5B57\u989C\u8272\u3002").addColorPicker((cp) => cp.setValue(this.plugin.settings.legendColor).onChange(async (v) => {
      this.plugin.settings.legendColor = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Card Background / \u5361\u7247\u80CC\u666F").addColorPicker((cp) => cp.setValue(this.plugin.settings.backgroundColor).onChange(async (v) => {
      this.plugin.settings.backgroundColor = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Image Background / \u56FE\u7247\u80CC\u666F").addColorPicker((cp) => cp.setValue(this.plugin.settings.imageBackgroundColor).onChange(async (v) => {
      this.plugin.settings.imageBackgroundColor = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Border Color").addColorPicker((cp) => cp.setValue(this.plugin.settings.borderColor).onChange(async (v) => {
      this.plugin.settings.borderColor = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Border Width").addText((t) => t.setValue(this.plugin.settings.borderWidth).onChange(async (v) => {
      this.plugin.settings.borderWidth = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Details Position").addDropdown(
      (d) => d.addOption("bottom", "Bottom").addOption("side", "Side (Right)").setValue(this.plugin.settings.detailsPosition).onChange(async (v) => {
        this.plugin.settings.detailsPosition = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Theme").addDropdown(
      (d) => d.addOption("standard", "Standard").addOption("dark", "Dark").addOption("academic", "Academic").addOption("vivid", "Vivid").setValue(this.plugin.settings.theme).onChange(async (v) => {
        this.plugin.settings.theme = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show Details").addToggle((t) => t.setValue(this.plugin.settings.showDetails).onChange(async (v) => {
      this.plugin.settings.showDetails = v;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Keyword Reference Table / \u5173\u952E\u8BCD\u53C2\u8003\u8868", style: "margin-top: 30px;" });
    const helpDiv = containerEl.createDiv({ cls: "rdkit-settings-help" });
    const tableHtml = `
        <table class="rdkit-help-table">
            <thead>
                <tr>
                    <th>Keyword (\u5173\u952E\u8BCD)</th>
                    <th>Type (\u7C7B\u578B)</th>
                    <th>Description (\u8BF4\u660E) / Example</th>
                </tr>
            </thead>
            <tbody>
                <!-- \u57FA\u7840\u914D\u7F6E -->
                <tr class="section-header"><td colspan="3">Structure & Text (\u7ED3\u6784\u4E0E\u6587\u672C)</td></tr>
                <tr><td>title / header</td><td>string</td><td>(New!) \u9876\u90E8\u6807\u9898\u680F\u6587\u5B57\u3002title="Reaction SMIRKS"</td></tr>
                <tr><td>legend</td><td>string</td><td>\u56FE\u7247\u4E0B\u65B9\u7684\u6807\u9898\u6587\u5B57\u3002legend="Aspirin"</td></tr>
                <tr><td>text</td><td>string</td><td>\u8BE6\u60C5\u9762\u677F\u4E2D\u663E\u793A\u7684 Markdown \u6587\u672C\u3002text="This is **aspirin**"</td></tr>
                <tr><td>width</td><td>num</td><td>\u751F\u6210\u56FE\u7247\u7684\u5BBD\u5EA6 (px)\u3002width=300</td></tr>
                <tr><td>height</td><td>num</td><td>\u751F\u6210\u56FE\u7247\u7684\u9AD8\u5EA6 (px)\u3002height=200</td></tr>
                
                <!-- \u7ED8\u56FE\u6837\u5F0F -->
                <tr class="section-header"><td colspan="3">Drawing Style (\u7ED8\u56FE\u6837\u5F0F)</td></tr>
                <tr><td>bondLineWidth</td><td>num</td><td>\u5316\u5B66\u952E\u7EBF\u6761\u7C97\u7EC6\u3002bondLineWidth=2</td></tr>
                <tr><td>scaleBondWidth</td><td>bool</td><td>\u662F\u5426\u7F29\u653E\u952E\u5BBD\u3002scaleBondWidth=true</td></tr>
                <tr><td>highlightBondWidthMultiplier</td><td>num</td><td>\u9AD8\u4EAE\u952E\u7684\u7C97\u7EC6\u500D\u7387\u3002highlightBondWidthMultiplier=12</td></tr>
                <tr><td>fixedBondLength</td><td>num</td><td>\u56FA\u5B9A\u952E\u957F\u3002fixedBondLength=30</td></tr>
                <tr><td>multipleBondOffset</td><td>num</td><td>\u591A\u91CD\u952E\u7684\u504F\u79FB\u91CF\u3002multipleBondOffset=0.15</td></tr>
                <tr><td>padding</td><td>num</td><td>\u56FE\u7247\u8FB9\u7F18\u7559\u767D\u3002padding=0.05</td></tr>
                <tr><td>rotate</td><td>num</td><td>\u65CB\u8F6C\u5206\u5B50\u89D2\u5EA6\u3002rotate=45</td></tr>
                <tr><td>addStereoAnnotation</td><td>bool</td><td>\u663E\u793A\u7ACB\u4F53\u5316\u5B66\u6807\u8BB0 (R/S, E/Z)\u3002addStereoAnnotation=true</td></tr>
                <tr><td>atomLabelDeuteriumTritium</td><td>bool</td><td>\u663E\u793A\u6C18/\u6C1A\u540C\u4F4D\u7D20\u6807\u7B7E\u3002</td></tr>
                
                <!-- \u989C\u8272\u63A7\u5236 -->
                <tr class="section-header"><td colspan="3">Colors (\u989C\u8272)</td></tr>
                <tr><td>backgroundColour</td><td>color</td><td>\u80CC\u666F\u989C\u8272\u3002backgroundColour="#FFFFFF" or [1,1,1,1]</td></tr>
                <tr><td>highlightColour</td><td>color</td><td>\u9AD8\u4EAE\u989C\u8272\u3002highlightColour="#FF0000"</td></tr>
                <tr><td>symbolColour</td><td>color</td><td>\u5143\u7D20\u7B26\u53F7\u989C\u8272\u3002symbolColour="#000000"</td></tr>
                <tr><td>legendColour</td><td>color</td><td>\u56FE\u4F8B\u6587\u5B57\u989C\u8272\u3002legendColour="#333333"</td></tr>
                <tr><td>clearBackground</td><td>bool</td><td>\u662F\u5426\u6E05\u9664\u80CC\u666F(\u900F\u660E)\u3002clearBackground=true</td></tr>

                <!-- \u9AD8\u4EAE\u4E0E\u539F\u5B50 -->
                <tr class="section-header"><td colspan="3">Highlights & Indices (\u9AD8\u4EAE\u4E0E\u7D22\u5F15)</td></tr>
                <tr><td>atoms / highlight</td><td>list</td><td>\u9AD8\u4EAE\u7684\u539F\u5B50\u7D22\u5F15\u5217\u8868\u3002atoms=[0, 1, 5]</td></tr>
                <tr><td>bonds</td><td>list</td><td>\u9AD8\u4EAE\u7684\u5316\u5B66\u952E\u7D22\u5F15\u5217\u8868\u3002bonds=[2, 4]</td></tr>
                <tr><td>atomLabels</td><td>json</td><td>\u81EA\u5B9A\u4E49\u539F\u5B50\u6807\u7B7E\u3002atomLabels={"0": "C1"}</td></tr>
                <tr><td>addAtomIndices</td><td>bool</td><td>\u663E\u793A\u6240\u6709\u539F\u5B50\u7D22\u5F15\u7F16\u53F7\u3002addAtomIndices=true</td></tr>
                <tr><td>addBondIndices</td><td>bool</td><td>\u663E\u793A\u6240\u6709\u5316\u5B66\u952E\u7D22\u5F15\u7F16\u53F7\u3002addBondIndices=true</td></tr>
                <tr><td>fillHighlights</td><td>bool</td><td>\u662F\u5426\u586B\u5145\u9AD8\u4EAE\u533A\u57DF\u3002fillHighlights=true</td></tr>
                <tr><td>atomHighlightsAreCircles</td><td>bool</td><td>\u9AD8\u4EAE\u662F\u5426\u4E3A\u5706\u5F62\u3002atomHighlightsAreCircles=true</td></tr>
                
                <!-- \u5B57\u4F53\u4E0E\u7F29\u653E -->
                <tr class="section-header"><td colspan="3">Fonts & Scales (\u5B57\u4F53\u4E0E\u7F29\u653E)</td></tr>
                <tr><td>annotationFontScale</td><td>num</td><td>\u6CE8\u91CA\u5B57\u4F53\u7F29\u653E\u3002annotationFontScale=0.7</td></tr>
                <tr><td>legendFontSize</td><td>num</td><td>\u56FE\u4F8B\u5B57\u4F53\u5927\u5C0F\u3002legendFontSize=20</td></tr>
                <tr><td>minFontSize</td><td>num</td><td>\u6700\u5C0F\u5B57\u4F53\u5927\u5C0F\u3002minFontSize=12</td></tr>
                <tr><td>maxFontSize</td><td>num</td><td>\u6700\u5927\u5B57\u4F53\u5927\u5C0F\u3002maxFontSize=30</td></tr>
                <tr><td>fontFile</td><td>string</td><td>\u5B57\u4F53\u6587\u4EF6\u8DEF\u5F84 (\u672C\u5730)\u3002</td></tr>
                
                <!-- \u9884\u5904\u7406 -->
                <tr class="section-header"><td colspan="3">Preprocessing (\u9884\u5904\u7406)</td></tr>
                <tr><td>prepareMolsBeforeDrawing</td><td>bool</td><td>\u7ED8\u56FE\u524D\u662F\u5426\u9884\u5904\u7406\u5206\u5B50(Kekulize\u7B49)\u3002</td></tr>
                <tr><td>centreMoleculesBeforeDrawing</td><td>bool</td><td>\u7ED8\u56FE\u524D\u662F\u5426\u5C45\u4E2D\u5206\u5B50\u3002</td></tr>
                <tr><td>explicitMethyl</td><td>bool</td><td>\u663E\u5F0F\u753B\u51FA\u7532\u57FA\u672B\u7AEF\u3002explicitMethyl=true</td></tr>
                <tr><td>includeRadicals</td><td>bool</td><td>\u5305\u542B\u81EA\u7531\u57FA\u3002</td></tr>
                <tr><td>dummiesAreAttachments</td><td>bool</td><td>\u865A\u539F\u5B50\u4F5C\u4E3A\u8FDE\u63A5\u70B9\u3002</td></tr>

                <!-- \u7279\u6B8A\u529F\u80FD -->
                <tr class="section-header"><td colspan="3">Plugin Specific (\u63D2\u4EF6\u4E13\u7528)</td></tr>
                <tr><td>details</td><td>bool</td><td>(\u63D2\u4EF6\u4E13\u7528) \u662F\u5426\u663E\u793A\u5C5E\u6027\u8BE6\u60C5\u9762\u677F\u3002details=false</td></tr>
            </tbody>
        </table>
        `;
    helpDiv.innerHTML = tableHtml;
  }
};

// mol2d-viewer/renderChild.ts
var import_obsidian2 = require("obsidian");
var RDKitRenderChild = class extends import_obsidian2.MarkdownRenderChild {
  constructor(container, source, plugin, sourcePath, mode = "smiles") {
    super(container);
    this.source = source.trim();
    this.plugin = plugin;
    this.sourcePath = sourcePath;
    this.mode = mode;
  }
  async onload() {
    await this.render();
    this.registerEvent(this.plugin.app.workspace.on("rdkit:refresh-renders", () => this.render()));
  }
  // 智能分割 Config 与 SMILES
  findConfigSeparator(line) {
    let bracketLevel = 0;
    let parenLevel = 0;
    for (let i = 0; i < line.length; i++) {
      const char = line[i];
      if (char === "[")
        bracketLevel++;
      else if (char === "]")
        bracketLevel--;
      else if (char === "(")
        parenLevel++;
      else if (char === ")")
        parenLevel--;
      else if (char === "," && bracketLevel === 0 && parenLevel === 0) {
        return i;
      }
    }
    return -1;
  }
  // 智能分割分子字符串，识别 '+' 但忽略 [Na+] 这种情况
  splitByPlus(str) {
    const parts = [];
    let bracketLevel = 0;
    let lastIdx = 0;
    for (let i = 0; i < str.length; i++) {
      const c = str[i];
      if (c === "[")
        bracketLevel++;
      else if (c === "]")
        bracketLevel--;
      else if (c === "+" && bracketLevel === 0) {
        parts.push(str.substring(lastIdx, i).trim());
        lastIdx = i + 1;
      }
    }
    parts.push(str.substring(lastIdx).trim());
    return parts.filter((p) => p);
  }
  parseSimpleConfig(configText) {
    const opts = {};
    if (!configText)
      return opts;
    let strToParse = configText;
    try {
      const jsonStart = configText.indexOf("{");
      if (jsonStart !== -1) {
        const jsonPart = configText.substring(jsonStart);
        const extra = JSON.parse(jsonPart);
        if (typeof extra === "object" && !Array.isArray(extra)) {
          Object.assign(opts, extra);
          strToParse = configText.substring(0, jsonStart).trim();
        }
      }
    } catch (e) {
    }
    const typeMap = {
      "addAtomIndices": "bool",
      "addBondIndices": "bool",
      "addStereoAnnotation": "bool",
      "atomHighlightsAreCircles": "bool",
      "atomLabelDeuteriumTritium": "bool",
      "centreMoleculesBeforeDrawing": "bool",
      "circleAtoms": "bool",
      "clearBackground": "bool",
      "continuousHighlight": "bool",
      "dummiesAreAttachments": "bool",
      "explicitMethyl": "bool",
      "fillHighlights": "bool",
      "includeAtomTags": "bool",
      "includeMetadata": "bool",
      "includeRadicals": "bool",
      "prepareMolsBeforeDrawing": "bool",
      "scaleBondWidth": "bool",
      "scaleHighlightBondWidth": "bool",
      "rotate": "num",
      "additionalAtomLabelPadding": "num",
      "annotationFontScale": "num",
      "bondLineWidth": "num",
      "fixedBondLength": "num",
      "fixedScale": "num",
      "flagCloseContactsDist": "num",
      "highlightBondWidthMultiplier": "num",
      "highlightRadius": "num",
      "legendFontSize": "num",
      "maxFontSize": "num",
      "minFontSize": "num",
      "multipleBondOffset": "num",
      "padding": "num",
      "width": "num",
      "height": "num",
      "offsetx": "num",
      "offsety": "num",
      "title": "string",
      "header": "string",
      "legend": "string",
      "fontFile": "string",
      "text": "string",
      "backgroundColour": "color",
      "highlightColour": "color",
      "legendColour": "color",
      "symbolColour": "color",
      "atoms": "list",
      "bonds": "list",
      "highlight": "list",
      "atomLabels": "json"
    };
    const args = [];
    let buffer = "";
    let inQuote = null;
    let bracketDepth = 0;
    for (let i = 0; i < strToParse.length; i++) {
      const char = strToParse[i];
      if (inQuote) {
        if (char === inQuote)
          inQuote = null;
        buffer += char;
      } else {
        if (char === '"' || char === "'") {
          inQuote = char;
          buffer += char;
        } else if (char === "[" || char === "{" || char === "(") {
          bracketDepth++;
          buffer += char;
        } else if (char === "]" || char === "}" || char === ")") {
          bracketDepth--;
          buffer += char;
        } else if (char === "," && bracketDepth === 0) {
          args.push(buffer.trim());
          buffer = "";
        } else {
          buffer += char;
        }
      }
    }
    if (buffer.trim())
      args.push(buffer.trim());
    for (const arg of args) {
      if (!arg)
        continue;
      const eqIdx = arg.indexOf("=");
      let key, val;
      if (eqIdx !== -1) {
        key = arg.substring(0, eqIdx).trim();
        val = arg.substring(eqIdx + 1).trim();
      } else {
        key = arg.trim();
        val = "true";
      }
      if (key === "details") {
        opts.showDetailsOverride = val.toLowerCase() === "true";
        continue;
      }
      if (key === "highlight")
        key = "atoms";
      key = key.replace(/^["']|["']$/g, "");
      const type = typeMap[key];
      if (type === "bool")
        opts[key] = val.toLowerCase() === "true";
      else if (type === "num") {
        const n = parseFloat(val);
        if (!isNaN(n))
          opts[key] = n;
      } else if (type === "string")
        opts[key] = val.replace(/^["']|["']$/g, "");
      else if (type === "color") {
        let cVal = val.replace(/^["']|["']$/g, "");
        if (cVal.startsWith("#"))
          opts[key] = this.hexToRgb(cVal);
        else {
          try {
            if (cVal.startsWith("["))
              opts[key] = JSON.parse(cVal);
          } catch (e) {
          }
        }
      } else if (type === "list") {
        try {
          opts[key] = JSON.parse(val);
        } catch (e) {
          const content = val.replace(/^\[|\]$/g, "");
          if (content.trim() === "")
            opts[key] = [];
          else
            opts[key] = content.split(",").map((x) => parseInt(x.trim())).filter((x) => !isNaN(x));
        }
      } else if (type === "json") {
        try {
          opts[key] = JSON.parse(val);
        } catch (e) {
        }
      } else {
        if (!isNaN(parseFloat(val)) && isFinite(Number(val)))
          opts[key] = parseFloat(val);
        else if (val.startsWith("[") || val.startsWith("{")) {
          try {
            opts[key] = JSON.parse(val);
          } catch (e) {
            opts[key] = val;
          }
        } else if (val.toLowerCase() === "true" || val.toLowerCase() === "false")
          opts[key] = val.toLowerCase() === "true";
        else
          opts[key] = val.replace(/^["']|["']$/g, "");
      }
    }
    return opts;
  }
  hexToRgb(hex) {
    let s = hex.replace("#", "");
    if (s.length === 3)
      s = s.split("").map((c) => c + c).join("");
    const r = parseInt(s.substring(0, 2), 16) / 255;
    const g = parseInt(s.substring(2, 4), 16) / 255;
    const b = parseInt(s.substring(4, 6), 16) / 255;
    return [r, g, b, 1];
  }
  toSubscript(numStr) {
    const subMap = { "0": "\u2080", "1": "\u2081", "2": "\u2082", "3": "\u2083", "4": "\u2084", "5": "\u2085", "6": "\u2086", "7": "\u2087", "8": "\u2088", "9": "\u2089" };
    return numStr.split("").map((c) => subMap[c] || c).join("");
  }
  getThemeOptions() {
    const theme = this.plugin.settings.theme;
    const isDarkMode = document.body.classList.contains("theme-dark");
    const textColor = isDarkMode ? [0.9, 0.9, 0.9, 1] : [0.1, 0.1, 0.1, 1];
    let customLegendColor = textColor;
    if (this.plugin.settings.legendColor.startsWith("#")) {
      customLegendColor = this.hexToRgb(this.plugin.settings.legendColor);
    }
    const base = {
      width: -1,
      height: -1,
      bondLineWidth: 2,
      symbolColour: textColor,
      legendColour: customLegendColor
    };
    switch (theme) {
      case "dark":
        return { ...base, backgroundColour: [0.1, 0.1, 0.1, 1], symbolColour: [1, 1, 1, 1] };
      case "academic":
        return { ...base, bondLineWidth: 1.5, atomLabelFontFace: "serif" };
      case "vivid":
        return { ...base, bondLineWidth: 3, prepareMolsBeforeDrawing: true };
      case "standard":
      default:
        return base;
    }
  }
  // 生成单分子数据
  getMolData(smiles, themeOpts, drawOpts) {
    const mol = window.RDKit.get_mol(smiles);
    if (!mol)
      return null;
    try {
      const subOpts = { ...themeOpts, ...drawOpts };
      delete subOpts.legend;
      let svgHtml = mol.get_svg_with_highlights(JSON.stringify(subOpts));
      svgHtml = svgHtml.replace(/width=["']\d+(?:\.\d+)?(?:px)?["']/i, "");
      svgHtml = svgHtml.replace(/height=["']\d+(?:\.\d+)?(?:px)?["']/i, "");
      svgHtml = svgHtml.replace(/<rect[^>]*fill:#FFFFFF[^>]*><\/rect>/gi, "");
      svgHtml = svgHtml.replace(/>([^<]+)</g, (match, content) => {
        const mappingRegex = /:(\d+)(\s*)$/;
        const parts = content.match(mappingRegex);
        if (parts) {
          const num = parts[1];
          const space = parts[2] || "";
          return `>${content.replace(mappingRegex, this.toSubscript(num) + space)}<`;
        }
        return match;
      });
      const descriptors = mol.get_descriptors();
      return {
        smiles,
        svg: svgHtml,
        descriptors: descriptors ? JSON.parse(descriptors) : null
      };
    } catch (e) {
      return null;
    } finally {
      mol.delete();
    }
  }
  // 合并 SVG 序列 [ {svg:...}, {type:'operator', char:'+'} ...]
  mergeSequence(items, defaultLegendColor) {
    const parser = new DOMParser();
    const serializer = new XMLSerializer();
    const parsedItems = items.map((item) => {
      if (item.type === "svg" && item.svg) {
        const doc = parser.parseFromString(item.svg, "image/svg+xml");
        const vb = doc.documentElement.getAttribute("viewBox");
        let w = 0, h = 0;
        if (vb) {
          const v = vb.split(/[\s,]+/).map(parseFloat);
          w = v[2];
          h = v[3];
        }
        return { ...item, doc, w, h };
      }
      return item;
    });
    const plusWidth = 30;
    const arrowWidth = 60;
    const gap = 10;
    const legendFontSize = 20;
    const legendPadding = 10;
    let totalWidth = 0;
    let maxMolHeight = 40;
    let hasLegend = false;
    parsedItems.forEach((item, idx) => {
      if (idx > 0)
        totalWidth += gap;
      if (item.type === "svg") {
        totalWidth += item.w;
        if (item.h > maxMolHeight)
          maxMolHeight = item.h;
        if (item.legend)
          hasLegend = true;
      } else if (item.type === "operator") {
        totalWidth += item.char === ">>" || item.char === "->" ? arrowWidth : plusWidth;
      }
    });
    const totalHeight = maxMolHeight + (hasLegend ? legendFontSize + legendPadding : 0);
    const masterDoc = document.implementation.createDocument("http://www.w3.org/2000/svg", "svg", null);
    const svgRoot = masterDoc.documentElement;
    svgRoot.setAttribute("viewBox", `0 0 ${totalWidth} ${totalHeight}`);
    svgRoot.setAttribute("xmlns", "http://www.w3.org/2000/svg");
    let currentX = 0;
    const midY = maxMolHeight / 2;
    parsedItems.forEach((item) => {
      if (item.type === "svg" && item.doc) {
        const g = masterDoc.createElementNS("http://www.w3.org/2000/svg", "g");
        const yOff = (maxMolHeight - item.h) / 2;
        g.setAttribute("transform", `translate(${currentX}, ${yOff})`);
        Array.from(item.doc.documentElement.childNodes).forEach((n) => g.appendChild(masterDoc.importNode(n, true)));
        svgRoot.appendChild(g);
        if (item.legend) {
          const text = masterDoc.createElementNS("http://www.w3.org/2000/svg", "text");
          text.textContent = item.legend;
          text.setAttribute("x", String(currentX + item.w / 2));
          text.setAttribute("y", String(maxMolHeight + legendPadding + legendFontSize / 2));
          text.setAttribute("text-anchor", "middle");
          text.setAttribute("dominant-baseline", "middle");
          text.setAttribute("font-size", `${legendFontSize}px`);
          text.setAttribute("font-family", "sans-serif");
          text.setAttribute("fill", item.legendColor || defaultLegendColor);
          svgRoot.appendChild(text);
        }
        currentX += item.w;
      } else if (item.type === "operator") {
        const width = item.char === ">>" || item.char === "->" ? arrowWidth : plusWidth;
        const gOp = masterDoc.createElementNS("http://www.w3.org/2000/svg", "g");
        const path = masterDoc.createElementNS("http://www.w3.org/2000/svg", "path");
        path.setAttribute("stroke", item.legendColor || defaultLegendColor);
        path.setAttribute("stroke-width", "2");
        path.setAttribute("fill", "none");
        if (item.char === "+") {
          const size = 8;
          const cx = currentX + width / 2;
          path.setAttribute("d", `M ${cx} ${midY - size} L ${cx} ${midY + size} M ${cx - size} ${midY} L ${cx + size} ${midY}`);
        } else {
          const startX = currentX;
          const endX = currentX + width;
          const arrHead = 5;
          path.setAttribute("d", `M ${startX} ${midY} L ${endX} ${midY} M ${endX - arrHead} ${midY - arrHead} L ${endX} ${midY} L ${endX - arrHead} ${midY + arrHead}`);
        }
        gOp.appendChild(path);
        svgRoot.appendChild(gOp);
        currentX += width;
      }
      currentX += gap;
    });
    return serializer.serializeToString(masterDoc);
  }
  async render() {
    this.containerEl.empty();
    this.containerEl.classList.add("rdkit-outer-container");
    const lines = this.source.split("\n").filter((line) => line.trim() !== "");
    if (this.mode === "reaction") {
      await this.renderReactionBlockMode(lines);
    } else {
      const isMultiLineRxn = lines.some((l) => l.trim() === "+" || l.trim() === ">>");
      if (isMultiLineRxn) {
        await this.renderMultiLineMode(lines);
      } else {
        await this.renderStandardMode(lines);
      }
    }
  }
  // 模式3：Reaction 专用模式（支持 @keyword= 或 @keywords=, -> 多重箭头）
  async renderReactionBlockMode(lines) {
    const wrapper = this.containerEl.createDiv({ cls: "rdkit-wrapper" });
    let globalOpts = {};
    let sequence = [];
    let startIndex = 0;
    if (lines.length > 0) {
      const firstLine = lines[0].trim();
      if (firstLine.startsWith("@keyword=") || firstLine.startsWith("@keywords=")) {
        const eqIdx = firstLine.indexOf("=");
        if (eqIdx !== -1) {
          const configStr = firstLine.substring(eqIdx + 1).trim();
          globalOpts = this.parseSimpleConfig(configStr);
          startIndex = 1;
        }
      }
    }
    for (let i = startIndex; i < lines.length; i++) {
      const line = lines[i].trim();
      if (line === "->") {
        sequence.push({ type: "operator", char: ">>" });
      } else if (line === "+") {
        sequence.push({ type: "operator", char: "+" });
      } else if (line === ">>") {
        sequence.push({ type: "operator", char: ">>" });
      } else {
        const sepIdx = this.findConfigSeparator(line);
        let smiles, localOptsStr;
        if (sepIdx !== -1) {
          smiles = line.substring(0, sepIdx).trim();
          localOptsStr = line.substring(sepIdx + 1).trim();
        } else {
          smiles = line;
          localOptsStr = "";
        }
        const localOpts = this.parseSimpleConfig(localOptsStr);
        sequence.push({ type: "mol", smiles, opts: localOpts });
      }
    }
    await this.renderReactionSequence(wrapper, sequence, globalOpts);
  }
  // 模式1：多行输入模式（支持全局/局部参数）- 兼容旧 smiles 块
  async renderMultiLineMode(lines) {
    const wrapper = this.containerEl.createDiv({ cls: "rdkit-wrapper" });
    let globalOpts = {};
    const sequence = [];
    let startIndex = 0;
    const firstLine = lines[0];
    if (!firstLine.includes(">>") && !firstLine.includes("+") && firstLine.includes("=")) {
      const sepIdx = this.findConfigSeparator(firstLine);
      globalOpts = this.parseSimpleConfig(firstLine);
      if (Object.keys(globalOpts).length > 0) {
        startIndex = 1;
      }
    }
    for (let i = startIndex; i < lines.length; i++) {
      const line = lines[i].trim();
      if (line === "+" || line === ">>") {
        sequence.push({ type: "operator", char: line });
      } else {
        const sepIdx = this.findConfigSeparator(line);
        let smiles, localOptsStr;
        if (sepIdx !== -1) {
          smiles = line.substring(0, sepIdx).trim();
          localOptsStr = line.substring(sepIdx + 1).trim();
        } else {
          smiles = line;
          localOptsStr = "";
        }
        const localOpts = this.parseSimpleConfig(localOptsStr);
        sequence.push({ type: "mol", smiles, opts: localOpts });
      }
    }
    await this.renderReactionSequence(wrapper, sequence, globalOpts);
  }
  // 模式2：标准模式（列表或单行反应式）
  async renderStandardMode(lines) {
    const isMultiMol = lines.length > 1;
    for (const line of lines) {
      const wrapper = this.containerEl.createDiv({ cls: "rdkit-wrapper" });
      const sepIdx = this.findConfigSeparator(line);
      let smilesStr, configStr;
      if (sepIdx !== -1) {
        smilesStr = line.substring(0, sepIdx).trim();
        configStr = line.substring(sepIdx + 1).trim();
      } else {
        smilesStr = line.trim();
        configStr = "";
      }
      const drawOpts = this.parseSimpleConfig(configStr);
      if (smilesStr.includes(">>")) {
        const parts = smilesStr.split(">>");
        const lhs = parts[0];
        const rhs = parts[1];
        const sequence = [];
        const rParts = this.splitByPlus(lhs);
        const pParts = this.splitByPlus(rhs);
        rParts.forEach((s, i) => {
          if (i > 0)
            sequence.push({ type: "operator", char: "+" });
          sequence.push({ type: "mol", smiles: s, opts: {} });
        });
        sequence.push({ type: "operator", char: ">>" });
        pParts.forEach((s, i) => {
          if (i > 0)
            sequence.push({ type: "operator", char: "+" });
          sequence.push({ type: "mol", smiles: s, opts: {} });
        });
        await this.renderReactionSequence(wrapper, sequence, drawOpts);
      } else {
        await this.renderSingleMolecule(wrapper, smilesStr, drawOpts, isMultiMol);
      }
    }
  }
  // 核心渲染流：反应式序列
  async renderReactionSequence(wrapper, sequence, globalOpts) {
    var _a;
    if (!window.RDKit) {
      wrapper.createEl("div", { text: "Loading RDKit...", cls: "rdkit-loading" });
      return;
    }
    const themeOpts = this.getThemeOptions();
    const parentWidth = this.containerEl.clientWidth > 0 ? this.containerEl.clientWidth : ((_a = this.containerEl.parentElement) == null ? void 0 : _a.clientWidth) || 800;
    const isMobile = parentWidth < 500;
    wrapper.classList.toggle("is-mobile", isMobile);
    wrapper.style.setProperty("--rdkit-border", `${this.plugin.settings.borderWidth} solid ${this.plugin.settings.borderColor}`);
    wrapper.style.setProperty("--rdkit-bg", this.plugin.settings.backgroundColor);
    if (!isMobile) {
      wrapper.style.width = this.plugin.settings.reactionContainerWidth;
    } else {
      wrapper.style.width = "100%";
    }
    const headerText = globalOpts.title || globalOpts.header;
    if (headerText) {
      const headerEl = wrapper.createDiv({ cls: "rdkit-card-header" });
      headerEl.innerText = headerText;
    }
    const svgContainer = wrapper.createDiv({ cls: "rdkit-img-container" });
    svgContainer.style.setProperty("--rdkit-img-bg", this.plugin.settings.imageBackgroundColor);
    if (!isMobile)
      svgContainer.style.width = "100%";
    const renderItems = [];
    const reactantsData = [];
    const productsData = [];
    let hasArrow = false;
    for (const item of sequence) {
      if (item.type === "operator") {
        if (item.char === ">>" || item.char === "->")
          hasArrow = true;
        renderItems.push(item);
      } else {
        const mergedOpts = { ...globalOpts, ...item.opts };
        const data = this.getMolData(item.smiles, themeOpts, mergedOpts);
        renderItems.push({
          type: "svg",
          svg: data == null ? void 0 : data.svg,
          w: 0,
          h: 0,
          legend: mergedOpts.legend,
          legendColor: mergedOpts.legendColor || mergedOpts.symbolColour || this.plugin.settings.legendColor
        });
        if (data && data.descriptors) {
          if (hasArrow)
            productsData.push({ desc: data.descriptors, label: item.smiles });
          else
            reactantsData.push({ desc: data.descriptors, label: item.smiles });
        }
      }
    }
    const mergedSvg = this.mergeSequence(renderItems, this.plugin.settings.legendColor);
    svgContainer.innerHTML = mergedSvg;
    if (globalOpts.legend) {
      const legendEl = wrapper.createDiv({ cls: "rdkit-legend-box" });
      legendEl.innerText = globalOpts.legend;
      legendEl.style.color = this.plugin.settings.legendColor;
      legendEl.style.textAlign = "center";
      legendEl.style.marginTop = "8px";
      legendEl.style.fontWeight = "600";
    }
    if (globalOpts.text || reactantsData.length > 0 || productsData.length > 0) {
      this.createDetailsPanel(wrapper, globalOpts.text, reactantsData, productsData);
    }
  }
  // 核心渲染流：单分子
  async renderSingleMolecule(wrapper, smilesStr, drawOpts, isMultiMol) {
    var _a;
    if (!window.RDKit)
      return;
    const themeOpts = this.getThemeOptions();
    const finalShowDetails = drawOpts.showDetailsOverride !== void 0 ? drawOpts.showDetailsOverride : this.plugin.settings.showDetails;
    const settingsPos = this.plugin.settings.detailsPosition;
    const effectivePosition = isMultiMol || finalShowDetails === false ? "bottom" : settingsPos;
    const isSide = effectivePosition === "side";
    const parentWidth = this.containerEl.clientWidth > 0 ? this.containerEl.clientWidth : ((_a = this.containerEl.parentElement) == null ? void 0 : _a.clientWidth) || 800;
    const isMobile = parentWidth < 500;
    wrapper.classList.toggle("is-side-layout", isSide);
    wrapper.classList.toggle("is-mobile", isMobile);
    wrapper.style.setProperty("--rdkit-border", `${this.plugin.settings.borderWidth} solid ${this.plugin.settings.borderColor}`);
    wrapper.style.setProperty("--rdkit-bg", this.plugin.settings.backgroundColor);
    if (!isMobile)
      wrapper.style.width = this.plugin.settings.containerWidth;
    const headerText = drawOpts.title || drawOpts.header;
    if (headerText) {
      const headerEl = wrapper.createDiv({ cls: "rdkit-card-header" });
      headerEl.innerText = headerText;
    }
    const svgContainer = wrapper.createDiv({ cls: "rdkit-img-container" });
    svgContainer.style.setProperty("--rdkit-img-bg", this.plugin.settings.imageBackgroundColor);
    if (!isMobile)
      svgContainer.style.width = this.plugin.settings.imageWidth;
    const mol = window.RDKit.get_mol(smilesStr);
    if (mol) {
      try {
        const svgConfig = JSON.stringify({ ...themeOpts, ...drawOpts });
        let svgHtml = mol.get_svg_with_highlights(svgConfig);
        if (drawOpts.legend) {
          const tempDiv = document.createElement("div");
          tempDiv.innerHTML = svgHtml;
          const texts = tempDiv.querySelectorAll("text");
          texts.forEach((t) => {
            if (t.textContent && t.textContent.includes(drawOpts.legend)) {
              t.style.fill = this.plugin.settings.legendColor;
            }
          });
          svgHtml = tempDiv.innerHTML;
        }
        svgContainer.innerHTML = svgHtml;
        const svgEl = svgContainer.querySelector("svg");
        if (svgEl) {
          svgEl.style.height = this.plugin.settings.imageHeight;
          const bgRect = svgEl.querySelector('rect[style*="fill:#FFFFFF"]');
          if (bgRect) {
            bgRect.style.fill = "transparent";
            bgRect.style.fillOpacity = "0";
          }
        }
        if (finalShowDetails) {
          const descStr = mol.get_descriptors();
          const desc = descStr ? JSON.parse(descStr) : null;
          if (desc) {
            const detailsWrapper = wrapper.createDiv({ cls: "rdkit-details-wrapper" });
            detailsWrapper.classList.toggle("details-side", isSide && !isMobile);
            if (isSide && !isMobile)
              detailsWrapper.style.maxHeight = this.plugin.settings.imageHeight === "auto" ? "300px" : this.plugin.settings.imageHeight;
            this.renderDescriptorsFromObj(detailsWrapper, desc, "Molecule Properties");
          }
        }
      } finally {
        mol.delete();
      }
    } else {
      wrapper.createEl("div", { text: `Invalid SMILES: ${smilesStr}`, cls: "rdkit-error" });
    }
  }
  createDetailsPanel(wrapper, customText, rData, pData) {
    const btn = wrapper.createEl("button", { text: "Show Reaction Details", cls: "rdkit-details-btn" });
    const detailsDiv = wrapper.createDiv({ cls: "rdkit-reaction-details", style: "display:none;" });
    btn.onclick = () => {
      const isHidden = detailsDiv.style.display === "none";
      detailsDiv.style.display = isHidden ? "block" : "none";
      btn.innerText = isHidden ? "Hide Reaction Details" : "Show Reaction Details";
    };
    if (customText) {
      const textEl = detailsDiv.createDiv({ cls: "rdkit-custom-text" });
      import_obsidian2.MarkdownRenderer.render(this.plugin.app, customText, textEl, this.sourcePath, this);
    }
    const colsContainer = detailsDiv.createDiv({ cls: "rdkit-reaction-cols" });
    if (rData.length > 0) {
      const rCol = colsContainer.createDiv({ cls: "rdkit-reaction-col" });
      rCol.createEl("h4", { text: "Reactants / Start (\u8D77\u59CB)", style: "margin: 0 0 10px 0;" });
      rData.forEach((d, i) => {
        this.renderDescriptorsFromObj(rCol, d.desc, d.label || `Molecule ${i + 1}`);
      });
    }
    if (pData.length > 0) {
      const pCol = colsContainer.createDiv({ cls: "rdkit-reaction-col" });
      pCol.createEl("h4", { text: "Products / End (\u4EA7\u7269)", style: "margin: 0 0 10px 0;" });
      pData.forEach((d, i) => {
        this.renderDescriptorsFromObj(pCol, d.desc, d.label || `Molecule ${i + 1}`);
      });
    }
  }
  renderDescriptorsFromObj(container, descriptors, title) {
    const keyMap = {
      "amw": "\u5E73\u5747\u5206\u5B50\u91CF (amw)",
      "exactmw": "\u7CBE\u786E\u5206\u5B50\u91CF (exactmw)",
      "formula": "\u5206\u5B50\u5F0F (formula)",
      "tpsa": "\u62D3\u6251\u6781\u6027\u8868\u9762\u79EF (tpsa)",
      "mollogp": "\u8102\u6C34\u5206\u914D\u7CFB\u6570 (mollogp)",
      "molmr": "\u6469\u5C14\u6298\u5C04\u7387 (molmr)",
      "labuteasa": "Labute \u8FD1\u4F3C\u8868\u9762\u79EF (labuteASA)",
      "crippenclogp": "Crippen ClogP (CrippenClogP)",
      "crippenmr": "Crippen \u6469\u5C14\u6298\u5C04 (CrippenMR)",
      "numrotatablebonds": "\u53EF\u65CB\u8F6C\u952E\u6570 (NumRotatableBonds)",
      "numhbd": "\u6C22\u952E\u4F9B\u4F53\u6570 (NumHBD)",
      "numhba": "\u6C22\u952E\u53D7\u4F53\u6570 (NumHBA)",
      "lipinskihba": "Lipinski \u6C22\u952E\u53D7\u4F53 (lipinskiHBA)",
      "lipinskihbd": "Lipinski \u6C22\u952E\u4F9B\u4F53 (lipinskiHBD)",
      "numheavyatoms": "\u91CD\u539F\u5B50\u6570 (NumHeavyAtoms)",
      "numatoms": "\u603B\u539F\u5B50\u6570 (NumAtoms)",
      "numheteroatoms": "\u6742\u539F\u5B50\u6570 (NumHeteroatoms)",
      "numamidebonds": "\u9170\u80FA\u952E\u6570 (NumAmideBonds)",
      "fractioncsp3": "Csp3 \u5206\u6570 (FractionCSP3)",
      "numrings": "\u73AF\u6570 (NumRings)",
      "numaromaticrings": "\u82B3\u9999\u73AF\u6570 (NumAromaticRings)",
      "numaliphaticrings": "\u8102\u80AA\u73AF\u6570 (NumAliphaticRings)",
      "numsaturatedrings": "\u9971\u548C\u73AF\u6570 (NumSaturatedRings)",
      "numheterocycles": "\u6742\u73AF\u6570 (NumHeterocycles)",
      "numaromaticheterocycles": "\u82B3\u9999\u6742\u73AF\u6570 (NumAromaticHeterocycles)",
      "numsaturatedheterocycles": "\u9971\u548C\u6742\u73AF\u6570 (NumSaturatedHeterocycles)",
      "numaliphaticheterocycles": "\u8102\u80AA\u6742\u73AF\u6570 (NumAliphaticHeterocycles)",
      "numspiroatoms": "\u87BA\u539F\u5B50\u6570 (NumSpiroAtoms)",
      "numbridgeheadatoms": "\u6865\u5934\u539F\u5B50\u6570 (NumBridgeheadAtoms)",
      "numatomstereocenters": "\u539F\u5B50\u7ACB\u4F53\u4E2D\u5FC3\u6570 (NumAtomStereoCenters)",
      "numunspecifiedatomstereocenters": "\u672A\u6307\u5B9A\u7ACB\u4F53\u4E2D\u5FC3\u6570 (NumUnspecifiedAtomStereoCenters)",
      "chi0v": "\u539F\u5B50\u4EF7\u8FDE\u63A5\u6027\u6307\u6570 (chi0v)",
      "chi1v": "\u4E00\u9636\u4EF7\u8FDE\u63A5\u6027\u6307\u6570 (chi1v)",
      "chi2v": "\u4E8C\u9636\u4EF7\u8FDE\u63A5\u6027\u6307\u6570 (chi2v)",
      "chi3v": "\u4E09\u9636\u4EF7\u8FDE\u63A5\u6027\u6307\u6570 (chi3v)",
      "chi4v": "\u56DB\u9636\u4EF7\u8FDE\u63A5\u6027\u6307\u6570 (chi4v)",
      "chi0n": "\u96F6\u9636\u8FDE\u63A5\u6027\u6307\u6570 (chi0n)",
      "chi1n": "\u4E00\u9636\u8FDE\u63A5\u6027\u6307\u6570 (chi1n)",
      "chi2n": "\u4E8C\u9636\u8FDE\u63A5\u6027\u6307\u6570 (chi2n)",
      "chi3n": "\u4E09\u9636\u8FDE\u63A5\u6027\u6307\u6570 (chi3n)",
      "chi4n": "\u56DB\u9636\u8FDE\u63A5\u6027\u6307\u6570 (chi4n)",
      "hallkieralpha": "Hall-Kier Alpha \u6307\u6570 (hallKierAlpha)",
      "kappa1": "Kappa1 \u6307\u6570 (kappa1)",
      "kappa2": "Kappa2 \u6307\u6570 (kappa2)",
      "kappa3": "Kappa3 \u6307\u6570 (kappa3)",
      "phi": "\u67D4\u6027\u6307\u6570 (Phi)"
    };
    const categories = {
      "\u57FA\u7840\u5C5E\u6027 (Basic)": ["amw", "exactmw", "formula", "tpsa", "labuteasa"],
      "\u836F\u6548/\u4EB2\u8102\u6027 (Drug-like)": ["mollogp", "molmr", "crippenclogp", "crippenmr", "fractioncsp3"],
      "\u6C22\u952E\u4E0E\u9170\u80FA\u952E (H-Bonds and Amide Bonds)": ["numhbd", "numhba", "lipinskihba", "lipinskihbd", "numamidebonds"],
      "\u8BA1\u6570\u5C5E\u6027 (Counts)": ["numatoms", "numheavyatoms", "numheteroatoms", "numspiroatoms", "numbridgeheadatoms"],
      "\u73AF\u7CFB\u7EDF (Rings)": ["numrings", "numaromaticrings", "numaliphaticrings", "numsaturatedrings", "numheterocycles", "numaromaticheterocycles"],
      "\u7ACB\u4F53\u4E0E\u62D3\u6251 (Topo/Stereo)": ["numatomstereocenters", "numunspecifiedatomstereocenters", "numrotatablebonds", "chi0v", "chi1v", "chi2v", "chi3v", "chi4v", "phi", "hallkieralpha", "kappa1", "kappa2", "kappa3"]
    };
    if (title) {
      const h5 = container.createEl("h5", { text: title });
      h5.style.marginTop = "10px";
      h5.style.marginBottom = "5px";
      h5.style.borderBottom = "1px solid var(--background-modifier-border)";
    }
    Object.keys(categories).forEach((catName) => {
      const keys = categories[catName];
      let availableKeysInCat = keys.filter((k) => descriptors.hasOwnProperty(Object.keys(descriptors).find((dk) => dk.toLowerCase() === k.toLowerCase()) || ""));
      if (availableKeysInCat.length > 0) {
        const detailsEl = container.createEl("details", { cls: "rdkit-details-cat" });
        if (catName.includes("Basic"))
          detailsEl.setAttribute("open", "");
        detailsEl.createEl("summary", { text: catName });
        const listContainer = detailsEl.createDiv({ cls: "rdkit-prop-list" });
        availableKeysInCat.forEach((k) => {
          const realKey = Object.keys(descriptors).find((dk) => dk.toLowerCase() === k.toLowerCase());
          const val = descriptors[realKey];
          const displayName = keyMap[k.toLowerCase()] || realKey;
          const item = listContainer.createDiv({ cls: "rdkit-prop-item" });
          item.createEl("strong", { text: displayName });
          item.createEl("span", { text: typeof val === "number" ? val.toFixed(2) : String(val) });
        });
      }
    });
  }
};

// mol2d-viewer/main.ts
var RDKitPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new RDKitSettingTab(this.app, this));
    try {
      const pluginDir = this.manifest.dir;
      const adapter = this.app.vault.adapter;
      const injectRDKit = (fileName) => {
        return new Promise((resolve) => {
          if (window.initRDKitModule)
            return resolve(window.initRDKitModule);
          const resourcePath = adapter.getResourcePath((0, import_obsidian3.normalizePath)(pluginDir + "/" + fileName));
          const script = document.createElement("script");
          script.src = resourcePath;
          script.type = "text/javascript";
          script.onload = () => resolve(window.initRDKitModule);
          script.onerror = () => resolve(null);
          document.head.appendChild(script);
        });
      };
      await injectRDKit("RDKit_minimal.js");
      if (window.initRDKitModule) {
        window.RDKit = await window.initRDKitModule({
          locateFile: (path) => {
            const wasmPath = (0, import_obsidian3.normalizePath)(pluginDir + "/" + path);
            return adapter.getResourcePath(wasmPath);
          }
        });
      }
      this.registerMarkdownCodeBlockProcessor("smiles", (source, el, ctx) => {
        const child = new RDKitRenderChild(el, source, this, ctx.sourcePath, "smiles");
        ctx.addChild(child);
      });
      this.registerMarkdownCodeBlockProcessor("reaction", (source, el, ctx) => {
        const child = new RDKitRenderChild(el, source, this, ctx.sourcePath, "reaction");
        ctx.addChild(child);
      });
      this.registerEvent(this.app.workspace.on("rdkit:update", () => {
        this.app.workspace.trigger("rdkit:refresh-renders");
      }));
    } catch (e) {
      console.error("RDKit Offline Initialization Failed", e);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.app.workspace.trigger("rdkit:update");
  }
};
