/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// mol2d-viewer/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RDKitPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// mol2d-viewer/settings.ts
var DEFAULT_SETTINGS = {
  bondColor: "#ffffff",
  containerWidth: "fit-content",
  reactionContainerWidth: "100%",
  imageWidth: "300px",
  imageHeight: "auto",
  showDetails: true,
  detailsPosition: "bottom",
  useLocalResourceOnly: true,
  theme: "standard",
  borderColor: "#cccccc",
  borderWidth: "1px",
  backgroundColor: "transparent",
  imageBackgroundColor: "transparent",
  legendColor: "var(--text-normal)",
  generate3D: false
};

// mol2d-viewer/settingTab.ts
var import_obsidian = require("obsidian");
var RDKitSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "RDKit Render Settings" });
    new import_obsidian.Setting(containerEl).setName("Container Layout Width").setDesc("Use 'fit-content' or fixed px/% value. / \u8FB9\u6846\u5305\u88F9\u5BBD\u5EA6\u8BBE\u7F6E\u3002").addText((t) => t.setValue(this.plugin.settings.containerWidth).onChange(async (v) => {
      this.plugin.settings.containerWidth = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Image Width / \u56FE\u7247\u5BBD\u5EA6").addText((t) => t.setValue(this.plugin.settings.imageWidth).onChange(async (v) => {
      this.plugin.settings.imageWidth = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Title (Legend) Color / \u6807\u9898\u6587\u5B57\u989C\u8272").setDesc("Color for the legend text. / \u72EC\u7ACB\u8BBE\u7F6E\u56FE\u7247\u4E0B\u65B9\u6807\u9898\u6587\u5B57\u989C\u8272\u3002").addColorPicker((cp) => cp.setValue(this.plugin.settings.legendColor).onChange(async (v) => {
      this.plugin.settings.legendColor = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Card Background / \u5361\u7247\u80CC\u666F").addColorPicker((cp) => cp.setValue(this.plugin.settings.backgroundColor).onChange(async (v) => {
      this.plugin.settings.backgroundColor = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Image Background / \u56FE\u7247\u80CC\u666F").addColorPicker((cp) => cp.setValue(this.plugin.settings.imageBackgroundColor).onChange(async (v) => {
      this.plugin.settings.imageBackgroundColor = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Border Color").addColorPicker((cp) => cp.setValue(this.plugin.settings.borderColor).onChange(async (v) => {
      this.plugin.settings.borderColor = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Border Width").addText((t) => t.setValue(this.plugin.settings.borderWidth).onChange(async (v) => {
      this.plugin.settings.borderWidth = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Details Position").addDropdown(
      (d) => d.addOption("bottom", "Bottom").addOption("side", "Side (Right)").setValue(this.plugin.settings.detailsPosition).onChange(async (v) => {
        this.plugin.settings.detailsPosition = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Theme").addDropdown(
      (d) => d.addOption("standard", "Standard").addOption("dark", "Dark").addOption("academic", "Academic").addOption("vivid", "Vivid").setValue(this.plugin.settings.theme).onChange(async (v) => {
        this.plugin.settings.theme = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show Details").addToggle((t) => t.setValue(this.plugin.settings.showDetails).onChange(async (v) => {
      this.plugin.settings.showDetails = v;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Keyword Reference Table / \u5173\u952E\u8BCD\u53C2\u8003\u8868", style: "margin-top: 30px;" });
    const helpDiv = containerEl.createDiv({ cls: "rdkit-settings-help" });
    const tableHtml = `
        <table class="rdkit-help-table">
            <thead>
                <tr>
                    <th>Keyword (\u5173\u952E\u8BCD)</th>
                    <th>Type (\u7C7B\u578B)</th>
                    <th>Description (\u8BF4\u660E) / Example</th>
                </tr>
            </thead>
            <tbody>
                <!-- \u57FA\u7840\u914D\u7F6E -->
                <tr class="section-header"><td colspan="3">Structure & Text (\u7ED3\u6784\u4E0E\u6587\u672C)</td></tr>
                <tr><td>title / header</td><td>string</td><td>(New!) \u9876\u90E8\u6807\u9898\u680F\u6587\u5B57\u3002title="Reaction SMIRKS"</td></tr>
                <tr><td>legend</td><td>string</td><td>\u56FE\u7247\u4E0B\u65B9\u7684\u6807\u9898\u6587\u5B57\u3002legend="Aspirin"</td></tr>
                <tr><td>text</td><td>string</td><td>\u8BE6\u60C5\u9762\u677F\u4E2D\u663E\u793A\u7684 Markdown \u6587\u672C\u3002text="This is **aspirin**"</td></tr>
                <tr><td>width</td><td>num</td><td>\u751F\u6210\u56FE\u7247\u7684\u5BBD\u5EA6 (px)\u3002width=300</td></tr>
                <tr><td>height</td><td>num</td><td>\u751F\u6210\u56FE\u7247\u7684\u9AD8\u5EA6 (px)\u3002height=200</td></tr>
                
                <!-- \u7ED8\u56FE\u6837\u5F0F -->
                <tr class="section-header"><td colspan="3">Drawing Style (\u7ED8\u56FE\u6837\u5F0F)</td></tr>
                <tr><td>bondLineWidth</td><td>num</td><td>\u5316\u5B66\u952E\u7EBF\u6761\u7C97\u7EC6\u3002bondLineWidth=2</td></tr>
                <tr><td>scaleBondWidth</td><td>bool</td><td>\u662F\u5426\u7F29\u653E\u952E\u5BBD\u3002scaleBondWidth=true</td></tr>
                <tr><td>highlightBondWidthMultiplier</td><td>num</td><td>\u9AD8\u4EAE\u952E\u7684\u7C97\u7EC6\u500D\u7387\u3002highlightBondWidthMultiplier=12</td></tr>
                <tr><td>fixedBondLength</td><td>num</td><td>\u56FA\u5B9A\u952E\u957F\u3002fixedBondLength=30</td></tr>
                <tr><td>multipleBondOffset</td><td>num</td><td>\u591A\u91CD\u952E\u7684\u504F\u79FB\u91CF\u3002multipleBondOffset=0.15</td></tr>
                <tr><td>padding</td><td>num</td><td>\u56FE\u7247\u8FB9\u7F18\u7559\u767D\u3002padding=0.05</td></tr>
                <tr><td>rotate</td><td>num</td><td>\u65CB\u8F6C\u5206\u5B50\u89D2\u5EA6\u3002rotate=45</td></tr>
                <tr><td>addStereoAnnotation</td><td>bool</td><td>\u663E\u793A\u7ACB\u4F53\u5316\u5B66\u6807\u8BB0 (R/S, E/Z)\u3002addStereoAnnotation=true</td></tr>
                <tr><td>atomLabelDeuteriumTritium</td><td>bool</td><td>\u663E\u793A\u6C18/\u6C1A\u540C\u4F4D\u7D20\u6807\u7B7E\u3002</td></tr>
                
                <!-- \u989C\u8272\u63A7\u5236 -->
                <tr class="section-header"><td colspan="3">Colors (\u989C\u8272)</td></tr>
                <tr><td>backgroundColour</td><td>color</td><td>\u80CC\u666F\u989C\u8272\u3002backgroundColour="#FFFFFF" or [1,1,1,1]</td></tr>
                <tr><td>highlightColour</td><td>color</td><td>\u9AD8\u4EAE\u989C\u8272\u3002highlightColour="#FF0000"</td></tr>
                <tr><td>symbolColour</td><td>color</td><td>\u5143\u7D20\u7B26\u53F7\u989C\u8272\u3002symbolColour="#000000"</td></tr>
                <tr><td>legendColour</td><td>color</td><td>\u56FE\u4F8B\u6587\u5B57\u989C\u8272\u3002legendColour="#333333"</td></tr>
                <tr><td>clearBackground</td><td>bool</td><td>\u662F\u5426\u6E05\u9664\u80CC\u666F(\u900F\u660E)\u3002clearBackground=true</td></tr>

                <!-- \u9AD8\u4EAE\u4E0E\u539F\u5B50 -->
                <tr class="section-header"><td colspan="3">Highlights & Indices (\u9AD8\u4EAE\u4E0E\u7D22\u5F15)</td></tr>
                <tr><td>atoms / highlight</td><td>list</td><td>\u9AD8\u4EAE\u7684\u539F\u5B50\u7D22\u5F15\u5217\u8868\u3002atoms=[0, 1, 5]</td></tr>
                <tr><td>bonds</td><td>list</td><td>\u9AD8\u4EAE\u7684\u5316\u5B66\u952E\u7D22\u5F15\u5217\u8868\u3002bonds=[2, 4]</td></tr>
                <tr><td>atomLabels</td><td>json</td><td>\u81EA\u5B9A\u4E49\u539F\u5B50\u6807\u7B7E\u3002atomLabels={"0": "C1"}</td></tr>
                <tr><td>addAtomIndices</td><td>bool</td><td>\u663E\u793A\u6240\u6709\u539F\u5B50\u7D22\u5F15\u7F16\u53F7\u3002addAtomIndices=true</td></tr>
                <tr><td>addBondIndices</td><td>bool</td><td>\u663E\u793A\u6240\u6709\u5316\u5B66\u952E\u7D22\u5F15\u7F16\u53F7\u3002addBondIndices=true</td></tr>
                <tr><td>fillHighlights</td><td>bool</td><td>\u662F\u5426\u586B\u5145\u9AD8\u4EAE\u533A\u57DF\u3002fillHighlights=true</td></tr>
                <tr><td>atomHighlightsAreCircles</td><td>bool</td><td>\u9AD8\u4EAE\u662F\u5426\u4E3A\u5706\u5F62\u3002atomHighlightsAreCircles=true</td></tr>
                
                <!-- \u5B57\u4F53\u4E0E\u7F29\u653E -->
                <tr class="section-header"><td colspan="3">Fonts & Scales (\u5B57\u4F53\u4E0E\u7F29\u653E)</td></tr>
                <tr><td>annotationFontScale</td><td>num</td><td>\u6CE8\u91CA\u5B57\u4F53\u7F29\u653E\u3002annotationFontScale=0.7</td></tr>
                <tr><td>legendFontSize</td><td>num</td><td>\u56FE\u4F8B\u5B57\u4F53\u5927\u5C0F\u3002legendFontSize=20</td></tr>
                <tr><td>minFontSize</td><td>num</td><td>\u6700\u5C0F\u5B57\u4F53\u5927\u5C0F\u3002minFontSize=12</td></tr>
                <tr><td>maxFontSize</td><td>num</td><td>\u6700\u5927\u5B57\u4F53\u5927\u5C0F\u3002maxFontSize=30</td></tr>
                <tr><td>fontFile</td><td>string</td><td>\u5B57\u4F53\u6587\u4EF6\u8DEF\u5F84 (\u672C\u5730)\u3002</td></tr>
                
                <!-- \u9884\u5904\u7406 -->
                <tr class="section-header"><td colspan="3">Preprocessing (\u9884\u5904\u7406)</td></tr>
                <tr><td>prepareMolsBeforeDrawing</td><td>bool</td><td>\u7ED8\u56FE\u524D\u662F\u5426\u9884\u5904\u7406\u5206\u5B50(Kekulize\u7B49)\u3002</td></tr>
                <tr><td>centreMoleculesBeforeDrawing</td><td>bool</td><td>\u7ED8\u56FE\u524D\u662F\u5426\u5C45\u4E2D\u5206\u5B50\u3002</td></tr>
                <tr><td>explicitMethyl</td><td>bool</td><td>\u663E\u5F0F\u753B\u51FA\u7532\u57FA\u672B\u7AEF\u3002explicitMethyl=true</td></tr>
                <tr><td>includeRadicals</td><td>bool</td><td>\u5305\u542B\u81EA\u7531\u57FA\u3002</td></tr>
                <tr><td>dummiesAreAttachments</td><td>bool</td><td>\u865A\u539F\u5B50\u4F5C\u4E3A\u8FDE\u63A5\u70B9\u3002</td></tr>

                <!-- \u7279\u6B8A\u529F\u80FD -->
                <tr class="section-header"><td colspan="3">Plugin Specific (\u63D2\u4EF6\u4E13\u7528)</td></tr>
                <tr><td>details</td><td>bool</td><td>(\u63D2\u4EF6\u4E13\u7528) \u662F\u5426\u663E\u793A\u5C5E\u6027\u8BE6\u60C5\u9762\u677F\u3002details=false</td></tr>
            </tbody>
        </table>
        `;
    helpDiv.innerHTML = tableHtml;
  }
};

// mol2d-viewer/renderChild.ts
var import_obsidian2 = require("obsidian");
var RDKitRenderChild = class extends import_obsidian2.MarkdownRenderChild {
  constructor(container, source, plugin, sourcePath, mode = "smiles") {
    super(container);
    this.source = source.trim();
    this.plugin = plugin;
    this.sourcePath = sourcePath;
    this.mode = mode;
  }
  async onload() {
    await this.render();
    this.registerEvent(this.plugin.app.workspace.on("rdkit:refresh-renders", () => this.render()));
    if (typeof ResizeObserver !== "undefined") {
      let resizeTimer = null;
      let lastWidth = this.containerEl.clientWidth;
      const resizeObserver = new ResizeObserver(() => {
        const w = this.containerEl.clientWidth;
        if (Math.abs(w - lastWidth) < 8)
          return;
        lastWidth = w;
        if (resizeTimer !== null)
          window.clearTimeout(resizeTimer);
        resizeTimer = window.setTimeout(() => {
          resizeTimer = null;
          if (this.containerEl.isConnected)
            this.render();
        }, 150);
      });
      resizeObserver.observe(this.containerEl);
      this.register(() => {
        resizeObserver.disconnect();
        if (resizeTimer !== null)
          window.clearTimeout(resizeTimer);
      });
    }
  }
  // 智能分割 Config 与 SMILES
  findConfigSeparator(line) {
    let bracketLevel = 0;
    let parenLevel = 0;
    for (let i = 0; i < line.length; i++) {
      const char = line[i];
      if (char === "[")
        bracketLevel++;
      else if (char === "]")
        bracketLevel--;
      else if (char === "(")
        parenLevel++;
      else if (char === ")")
        parenLevel--;
      else if (char === "," && bracketLevel === 0 && parenLevel === 0) {
        return i;
      }
    }
    return -1;
  }
  // 智能分割分子字符串，识别 '+' 但忽略 [Na+] 这种情况
  splitByPlus(str) {
    const parts = [];
    let bracketLevel = 0;
    let lastIdx = 0;
    for (let i = 0; i < str.length; i++) {
      const c = str[i];
      if (c === "[")
        bracketLevel++;
      else if (c === "]")
        bracketLevel--;
      else if (c === "+" && bracketLevel === 0) {
        parts.push(str.substring(lastIdx, i).trim());
        lastIdx = i + 1;
      }
    }
    parts.push(str.substring(lastIdx).trim());
    return parts.filter((p) => p);
  }
  parseSimpleConfig(configText) {
    const opts = {};
    if (!configText)
      return opts;
    let strToParse = configText;
    try {
      const jsonStart = configText.indexOf("{");
      if (jsonStart !== -1) {
        const jsonPart = configText.substring(jsonStart);
        const extra = JSON.parse(jsonPart);
        if (typeof extra === "object" && !Array.isArray(extra)) {
          Object.assign(opts, extra);
          strToParse = configText.substring(0, jsonStart).trim();
        }
      }
    } catch (e) {
    }
    const typeMap = {
      "addAtomIndices": "bool",
      "addBondIndices": "bool",
      "addStereoAnnotation": "bool",
      "atomHighlightsAreCircles": "bool",
      "atomLabelDeuteriumTritium": "bool",
      "centreMoleculesBeforeDrawing": "bool",
      "circleAtoms": "bool",
      "clearBackground": "bool",
      "continuousHighlight": "bool",
      "dummiesAreAttachments": "bool",
      "explicitMethyl": "bool",
      "fillHighlights": "bool",
      "includeAtomTags": "bool",
      "includeMetadata": "bool",
      "includeRadicals": "bool",
      "prepareMolsBeforeDrawing": "bool",
      "scaleBondWidth": "bool",
      "scaleHighlightBondWidth": "bool",
      "rotate": "num",
      "additionalAtomLabelPadding": "num",
      "annotationFontScale": "num",
      "bondLineWidth": "num",
      "fixedBondLength": "num",
      "fixedScale": "num",
      "flagCloseContactsDist": "num",
      "highlightBondWidthMultiplier": "num",
      "highlightRadius": "num",
      "legendFontSize": "num",
      "maxFontSize": "num",
      "minFontSize": "num",
      "multipleBondOffset": "num",
      "padding": "num",
      "width": "num",
      "height": "num",
      "offsetx": "num",
      "offsety": "num",
      "title": "string",
      "header": "string",
      "legend": "string",
      "fontFile": "string",
      "text": "string",
      "backgroundColour": "color",
      "highlightColour": "color",
      "legendColour": "color",
      "symbolColour": "color",
      "atoms": "list",
      "bonds": "list",
      "highlight": "list",
      "atomLabels": "json"
    };
    const args = [];
    let buffer = "";
    let inQuote = null;
    let bracketDepth = 0;
    for (let i = 0; i < strToParse.length; i++) {
      const char = strToParse[i];
      if (inQuote) {
        if (char === inQuote)
          inQuote = null;
        buffer += char;
      } else {
        if (char === '"' || char === "'") {
          inQuote = char;
          buffer += char;
        } else if (char === "[" || char === "{" || char === "(") {
          bracketDepth++;
          buffer += char;
        } else if (char === "]" || char === "}" || char === ")") {
          bracketDepth--;
          buffer += char;
        } else if (char === "," && bracketDepth === 0) {
          args.push(buffer.trim());
          buffer = "";
        } else {
          buffer += char;
        }
      }
    }
    if (buffer.trim())
      args.push(buffer.trim());
    for (const arg of args) {
      if (!arg)
        continue;
      const eqIdx = arg.indexOf("=");
      let key, val;
      if (eqIdx !== -1) {
        key = arg.substring(0, eqIdx).trim();
        val = arg.substring(eqIdx + 1).trim();
      } else {
        key = arg.trim();
        val = "true";
      }
      if (key === "details") {
        opts.showDetailsOverride = val.toLowerCase() === "true";
        continue;
      }
      if (key === "highlight")
        key = "atoms";
      key = key.replace(/^["']|["']$/g, "");
      const type = typeMap[key];
      if (type === "bool")
        opts[key] = val.toLowerCase() === "true";
      else if (type === "num") {
        const n = parseFloat(val);
        if (!isNaN(n))
          opts[key] = n;
      } else if (type === "string")
        opts[key] = val.replace(/^["']|["']$/g, "");
      else if (type === "color") {
        let cVal = val.replace(/^["']|["']$/g, "");
        if (cVal.startsWith("#"))
          opts[key] = this.hexToRgb(cVal);
        else {
          try {
            if (cVal.startsWith("["))
              opts[key] = JSON.parse(cVal);
          } catch (e) {
          }
        }
      } else if (type === "list") {
        try {
          opts[key] = JSON.parse(val);
        } catch (e) {
          const content = val.replace(/^\[|\]$/g, "");
          if (content.trim() === "")
            opts[key] = [];
          else
            opts[key] = content.split(",").map((x) => parseInt(x.trim())).filter((x) => !isNaN(x));
        }
      } else if (type === "json") {
        try {
          opts[key] = JSON.parse(val);
        } catch (e) {
        }
      } else {
        if (!isNaN(parseFloat(val)) && isFinite(Number(val)))
          opts[key] = parseFloat(val);
        else if (val.startsWith("[") || val.startsWith("{")) {
          try {
            opts[key] = JSON.parse(val);
          } catch (e) {
            opts[key] = val;
          }
        } else if (val.toLowerCase() === "true" || val.toLowerCase() === "false")
          opts[key] = val.toLowerCase() === "true";
        else
          opts[key] = val.replace(/^["']|["']$/g, "");
      }
    }
    return opts;
  }
  hexToRgb(hex) {
    let s = hex.replace("#", "");
    if (s.length === 3)
      s = s.split("").map((c) => c + c).join("");
    const r = parseInt(s.substring(0, 2), 16) / 255;
    const g = parseInt(s.substring(2, 4), 16) / 255;
    const b = parseInt(s.substring(4, 6), 16) / 255;
    return [r, g, b, 1];
  }
  toSubscript(numStr) {
    const subMap = { "0": "\u2080", "1": "\u2081", "2": "\u2082", "3": "\u2083", "4": "\u2084", "5": "\u2085", "6": "\u2086", "7": "\u2087", "8": "\u2088", "9": "\u2089" };
    return numStr.split("").map((c) => subMap[c] || c).join("");
  }
  getThemeOptions() {
    const theme = this.plugin.settings.theme;
    const isDarkMode = document.body.classList.contains("theme-dark");
    const textColor = isDarkMode ? [0.9, 0.9, 0.9, 1] : [0.1, 0.1, 0.1, 1];
    let customLegendColor = textColor;
    if (this.plugin.settings.legendColor.startsWith("#")) {
      customLegendColor = this.hexToRgb(this.plugin.settings.legendColor);
    }
    const base = {
      width: -1,
      height: -1,
      bondLineWidth: 2,
      symbolColour: textColor,
      legendColour: customLegendColor
    };
    switch (theme) {
      case "dark":
        return { ...base, backgroundColour: [0.1, 0.1, 0.1, 1], symbolColour: [1, 1, 1, 1] };
      case "academic":
        return { ...base, bondLineWidth: 1.5, atomLabelFontFace: "serif" };
      case "vivid":
        return { ...base, bondLineWidth: 3, prepareMolsBeforeDrawing: true };
      case "standard":
      default:
        return base;
    }
  }
  // 生成单分子数据
  getMolData(smiles, themeOpts, drawOpts) {
    const mol = window.RDKit.get_mol(smiles);
    if (!mol)
      return null;
    try {
      const subOpts = { ...themeOpts, ...drawOpts };
      delete subOpts.legend;
      let svgHtml = mol.get_svg_with_highlights(JSON.stringify(subOpts));
      svgHtml = svgHtml.replace(/width=["']\d+(?:\.\d+)?(?:px)?["']/i, "");
      svgHtml = svgHtml.replace(/height=["']\d+(?:\.\d+)?(?:px)?["']/i, "");
      svgHtml = svgHtml.replace(/<rect[^>]*fill:#FFFFFF[^>]*><\/rect>/gi, "");
      svgHtml = svgHtml.replace(/>([^<]+)</g, (match, content) => {
        const mappingRegex = /:(\d+)(\s*)$/;
        const parts = content.match(mappingRegex);
        if (parts) {
          const num = parts[1];
          const space = parts[2] || "";
          return `>${content.replace(mappingRegex, this.toSubscript(num) + space)}<`;
        }
        return match;
      });
      const descriptors = mol.get_descriptors();
      return {
        smiles,
        svg: svgHtml,
        descriptors: descriptors ? JSON.parse(descriptors) : null
      };
    } catch (e) {
      return null;
    } finally {
      mol.delete();
    }
  }
  // 解析操作符行：+ 、 -> 、 >> ，箭头支持 [上方标注][下方标注]（参考 chemfig/alchemist 的箭头条件写法）
  // 标注内允许嵌套方括号（如 SMILES 里的 [Cr]、[Na+]）：->[mol:O=[Cr](=O)(=O)O][加热]
  parseOperatorLine(line) {
    const m = line.match(/^(\+|->|>>)(.*)$/);
    if (!m)
      return null;
    const rest = m[2];
    const labels = [];
    let i = 0;
    while (i < rest.length) {
      if (/\s/.test(rest[i])) {
        i++;
        continue;
      }
      if (rest[i] !== "[")
        return null;
      let depth = 0, j = i;
      for (; j < rest.length; j++) {
        if (rest[j] === "[")
          depth++;
        else if (rest[j] === "]" && --depth === 0) {
          j++;
          break;
        }
      }
      if (depth !== 0)
        return null;
      labels.push(rest.slice(i + 1, j - 1).trim());
      if (labels.length > 2)
        return null;
      i = j;
    }
    const char = m[1] === "->" ? ">>" : m[1];
    if (char === "+")
      return labels.length === 0 ? { char } : null;
    return { char, above: labels[0] || void 0, below: labels[1] || void 0 };
  }
  // 标注文本轻量排版：分子式下标（H2SO4 → H₂SO₄）、^ 上标（如 SO4^2- 电荷）、
  // **粗体**、*斜体*、`代码`；整段被 $...$ 包裹时走 LaTeX（MathJax SVG 输出，保持矢量）
  parseLabelRuns(text) {
    const runs = [];
    const pushChem = (chunk, style) => {
      const chemRegex = /\^([-+0-9A-Za-z.]+)|([A-Za-z)\]])(\d+(?:\.\d+)?)/g;
      let l = 0;
      let m2;
      while ((m2 = chemRegex.exec(chunk)) !== null) {
        if (m2.index > l)
          runs.push({ ...style, text: chunk.slice(l, m2.index) });
        if (m2[1] !== void 0) {
          runs.push({ ...style, text: m2[1], shift: "sup" });
        } else {
          runs.push({ ...style, text: m2[2] });
          runs.push({ ...style, text: m2[3], shift: "sub" });
        }
        l = m2.index + m2[0].length;
      }
      if (l < chunk.length)
        runs.push({ ...style, text: chunk.slice(l) });
    };
    const mdRegex = /\*\*([^*]+)\*\*|\*([^*]+)\*|`([^`]+)`/g;
    let last = 0;
    let m;
    while ((m = mdRegex.exec(text)) !== null) {
      if (m.index > last)
        pushChem(text.slice(last, m.index), {});
      if (m[1] !== void 0)
        pushChem(m[1], { bold: true });
      else if (m[2] !== void 0)
        pushChem(m[2], { italic: true });
      else
        pushChem(m[3], { code: true });
      last = m.index + m[0].length;
    }
    if (last < text.length)
      pushChem(text.slice(last), {});
    return runs;
  }
  // 内置 mini-TeX 子集排版：$...$ 标注不依赖 MathJax 也能正确渲染。
  // 支持希腊字母（\Delta→Δ）、\mathrm/\text/\mathbf/\mathit 分组、^/_ 上下标（含 {} 分组）、
  // 常用符号（\circ→°、\times、\to 等）与间距命令（\, \; \:）。反应条件标注（温度、催化剂、Δ）全覆盖。
  parseTexRuns(tex) {
    const GREEK = { alpha: "\u03B1", beta: "\u03B2", gamma: "\u03B3", delta: "\u03B4", epsilon: "\u03B5", zeta: "\u03B6", eta: "\u03B7", theta: "\u03B8", iota: "\u03B9", kappa: "\u03BA", lambda: "\u03BB", mu: "\u03BC", nu: "\u03BD", xi: "\u03BE", pi: "\u03C0", rho: "\u03C1", sigma: "\u03C3", tau: "\u03C4", phi: "\u03C6", chi: "\u03C7", psi: "\u03C8", omega: "\u03C9", Gamma: "\u0393", Delta: "\u0394", Theta: "\u0398", Lambda: "\u039B", Xi: "\u039E", Pi: "\u03A0", Sigma: "\u03A3", Phi: "\u03A6", Psi: "\u03A8", Omega: "\u03A9" };
    const SYMBOLS = { circ: "\xB0", times: "\xD7", cdot: "\xB7", pm: "\xB1", to: "\u2192", rightarrow: "\u2192", leftarrow: "\u2190", leq: "\u2264", le: "\u2264", geq: "\u2265", ge: "\u2265", neq: "\u2260", approx: "\u2248", infty: "\u221E", ",": " ", ";": " ", ":": " ", "!": "", " ": " " };
    const runs = [];
    let i = 0;
    const n = tex.length;
    let style = {};
    const push = (text, extra = {}) => {
      if (text)
        runs.push({ ...style, ...extra, text });
    };
    const readAtom = () => {
      if (i >= n)
        return;
      const c = tex[i];
      if (c === "{") {
        i++;
        parseUntil("}");
        return;
      }
      if (c === "\\") {
        readCommand();
        return;
      }
      push(c);
      i++;
    };
    const readCommand = () => {
      i++;
      let name = "";
      while (i < n && /[A-Za-z]/.test(tex[i]))
        name += tex[i++];
      if (!name && i < n) {
        const ch = tex[i++];
        push(ch in SYMBOLS ? SYMBOLS[ch] : ch);
        return;
      }
      if (name in GREEK) {
        push(GREEK[name]);
        return;
      }
      if (name in SYMBOLS) {
        push(SYMBOLS[name]);
        return;
      }
      if (["mathrm", "text", "mathbf", "mathit", "bf", "it", "rm"].includes(name)) {
        const prev = style;
        if (name === "mathbf" || name === "bf")
          style = { ...style, bold: true };
        else if (name === "mathit" || name === "it")
          style = { ...style, italic: true };
        if (i < n && tex[i] === "{") {
          i++;
          parseUntil("}");
        } else
          readAtom();
        style = prev;
        return;
      }
    };
    const parseUntil = (end) => {
      while (i < n) {
        const c = tex[i];
        if (end && c === end) {
          i++;
          return;
        }
        if (c === "^" || c === "_") {
          const shift = c === "^" ? "sup" : "sub";
          i++;
          const before = runs.length;
          readAtom();
          for (let k = before; k < runs.length; k++)
            runs[k] = { ...runs[k], shift };
          continue;
        }
        if (c === "\\") {
          readCommand();
          continue;
        }
        if (c === "{") {
          i++;
          parseUntil("}");
          continue;
        }
        if (c === "}") {
          i++;
          return;
        }
        if (/\s/.test(c)) {
          push(" ");
          i++;
          continue;
        }
        push(c);
        i++;
      }
    };
    parseUntil();
    const merged = [];
    for (const r of runs) {
      const lastR = merged[merged.length - 1];
      if (lastR && lastR.bold === r.bold && lastR.italic === r.italic && lastR.shift === r.shift)
        lastR.text += r.text;
      else
        merged.push(r);
    }
    return merged;
  }
  // 合并 SVG 序列 [ {svg:...}, {type:'operator', char:'+'} ...]
  async mergeSequence(items, defaultLegendColor) {
    var _a;
    const parser = new DOMParser();
    const serializer = new XMLSerializer();
    const S = 1.6;
    const trimSvgDoc = (doc) => {
      try {
        const host = document.createElement("div");
        host.style.cssText = "position:absolute;visibility:hidden;left:-99999px;top:-99999px;";
        document.body.appendChild(host);
        const liveSvg = host.appendChild(doc.documentElement.cloneNode(true));
        liveSvg.querySelectorAll("rect").forEach((r) => r.remove());
        if (typeof liveSvg.getBBox === "function") {
          const bb = liveSvg.getBBox();
          const m = 4;
          if (bb.width > 0 && bb.height > 0) {
            doc.documentElement.setAttribute("viewBox", `${bb.x - m} ${bb.y - m} ${bb.width + 2 * m} ${bb.height + 2 * m}`);
            host.remove();
            return { w: bb.width + 2 * m, h: bb.height + 2 * m };
          }
        }
        host.remove();
      } catch (e) {
      }
      const vb = doc.documentElement.getAttribute("viewBox");
      if (vb) {
        const v = vb.split(/[\s,]+/).map(parseFloat);
        return { w: v[2], h: v[3] };
      }
      return { w: 0, h: 0 };
    };
    const parsedItems = items.map((item) => {
      if (item.type === "svg") {
        if (!item.svg)
          return { ...item, doc: null, w: 0, h: 0 };
        const doc = parser.parseFromString(item.svg, "image/svg+xml");
        const { w, h } = trimSvgDoc(doc);
        return { ...item, doc, w: w * S, h: h * S };
      }
      return item;
    });
    const plusWidth = 30 * S;
    const arrowWidth = 60 * S;
    const gap = 10 * S;
    const legendPadding = 10 * S;
    let maxMolHeight = 40 * S;
    parsedItems.forEach((item) => {
      if (item.type === "svg" && item.h > maxMolHeight)
        maxMolHeight = item.h;
    });
    const arrowLabelFontSize = Math.round(Math.min(30, Math.max(16, maxMolHeight * 0.28)));
    const arrowLabelPad = Math.round(arrowLabelFontSize * 1.5);
    const legendFontSize = Math.round(Math.min(26, Math.max(13, maxMolHeight * 0.2)));
    const estTextWidth = (s, fs) => {
      let w = 0;
      for (const ch of s)
        w += (ch.codePointAt(0) || 0) > 11903 ? fs : /[A-Z0-9]/.test(ch) ? fs * 0.68 : fs * 0.55;
      return w;
    };
    const estRunsWidth = (runs) => {
      let w = 0;
      for (const run of runs) {
        const fs = run.shift ? arrowLabelFontSize * 0.7 : arrowLabelFontSize;
        for (const ch of run.text)
          w += (ch.codePointAt(0) || 0) > 11903 ? fs : fs * 0.55;
      }
      return w;
    };
    const pxPerEx = arrowLabelFontSize * 0.5;
    const rxnDrawOpts = { ...this.getThemeOptions(), fixedBondLength: 30 };
    for (const item of parsedItems) {
      if (item.type !== "operator")
        continue;
      for (const key of ["above", "below"]) {
        const label = item[key];
        if (!label)
          continue;
        const trimmed = label.trim();
        const molMatch = trimmed.match(/^mol:(.+)$/);
        if (molMatch) {
          const data = this.getMolData(molMatch[1].trim(), rxnDrawOpts, {});
          if (data && data.svg) {
            const doc = parser.parseFromString(data.svg, "image/svg+xml");
            const { w, h } = trimSvgDoc(doc);
            if (w > 0 && h > 0) {
              item[key + "Mol"] = { doc, w: w * S, h: h * S };
              continue;
            }
          }
          item[key] = molMatch[1].trim();
          continue;
        }
        const m = trimmed.match(/^\$([\s\S]+)\$$/);
        if (!m)
          continue;
        const tex = m[1];
        let done = false;
        const mjNow = window.MathJax;
        if (mjNow && typeof mjNow.tex2svgPromise === "function") {
          try {
            const container = await mjNow.tex2svgPromise(tex, { display: false });
            const svgNode = container.querySelector ? container.querySelector("svg") : ((_a = container.firstElementChild) == null ? void 0 : _a.tagName) === "svg" ? container.firstElementChild : null;
            if (svgNode) {
              const exW = parseFloat(svgNode.getAttribute("width") || "0");
              const exH = parseFloat(svgNode.getAttribute("height") || "1");
              item[key + "Latex"] = { node: svgNode, w: exW * pxPerEx, h: exH * pxPerEx };
              done = true;
            }
          } catch (e) {
            console.warn("[mol2d] tex2svg \u5931\u8D25\uFF0C\u8F6C mini-TeX:", tex, e);
          }
        }
        if (!done) {
          const runs = this.parseTexRuns(tex);
          if (runs.length > 0) {
            item[key + "Runs"] = runs;
            done = true;
          }
        }
        if (!done)
          item[key] = tex;
      }
    }
    const labelWidthOf = (item, key) => {
      const mol = item[key + "Mol"];
      if (mol)
        return mol.w;
      const lat = item[key + "Latex"];
      if (lat)
        return lat.w;
      const runs = item[key + "Runs"];
      if (runs)
        return estRunsWidth(runs);
      return item[key] ? estRunsWidth(this.parseLabelRuns(item[key])) : 0;
    };
    let hasLegend = false;
    parsedItems.forEach((item) => {
      if (item.type === "svg") {
        item.effW = item.w;
        item.effH = item.h;
        if (item.legend)
          hasLegend = true;
      } else if (item.type === "operator") {
        if (item.char === ">>" || item.char === "->") {
          const labelW = Math.max(labelWidthOf(item, "above"), labelWidthOf(item, "below"));
          item.width = Math.max(arrowWidth, labelW + 16);
        } else {
          item.width = plusWidth;
        }
      }
    });
    const labelSpaceOf = (key) => Math.max(0, ...parsedItems.filter((i) => i.type === "operator").map((i) => {
      if (i[key + "Mol"])
        return i[key + "Mol"].h + 8;
      if (i[key + "Latex"])
        return i[key + "Latex"].h + 8;
      return i[key + "Runs"] || i[key] ? arrowLabelPad : 0;
    }));
    const topPad = labelSpaceOf("above");
    const bottomPad = labelSpaceOf("below");
    const legendArea = hasLegend ? legendFontSize + legendPadding : 0;
    const totalHeight = topPad + maxMolHeight + bottomPad + legendArea;
    let totalWidth = 0;
    parsedItems.forEach((item, idx) => {
      if (idx > 0)
        totalWidth += gap;
      totalWidth += item.type === "svg" ? item.effW : item.width;
    });
    const masterDoc = document.implementation.createDocument("http://www.w3.org/2000/svg", "svg", null);
    const svgRoot = masterDoc.documentElement;
    svgRoot.setAttribute("viewBox", `0 0 ${totalWidth} ${totalHeight}`);
    svgRoot.setAttribute("xmlns", "http://www.w3.org/2000/svg");
    let currentX = 0;
    const midY = topPad + maxMolHeight / 2;
    const pendingLegends = [];
    parsedItems.forEach((item) => {
      if (item.type === "svg" && item.doc) {
        const g = masterDoc.createElementNS("http://www.w3.org/2000/svg", "g");
        const yOff = topPad + (maxMolHeight - item.effH) / 2;
        g.setAttribute("transform", `translate(${currentX}, ${yOff}) scale(${S})`);
        Array.from(item.doc.documentElement.childNodes).forEach((n) => g.appendChild(masterDoc.importNode(n, true)));
        svgRoot.appendChild(g);
        if (item.legend) {
          pendingLegends.push({
            text: String(item.legend),
            cx: currentX + item.effW / 2,
            color: item.legendColor || defaultLegendColor
          });
        }
        currentX += item.effW;
      } else if (item.type === "operator") {
        const width = item.width;
        const gOp = masterDoc.createElementNS("http://www.w3.org/2000/svg", "g");
        const path = masterDoc.createElementNS("http://www.w3.org/2000/svg", "path");
        path.setAttribute("stroke", item.legendColor || defaultLegendColor);
        path.setAttribute("stroke-width", "2");
        path.setAttribute("fill", "none");
        if (item.char === "+") {
          const size = 8;
          const cx = currentX + width / 2;
          path.setAttribute("d", `M ${cx} ${midY - size} L ${cx} ${midY + size} M ${cx - size} ${midY} L ${cx + size} ${midY}`);
        } else {
          const startX = currentX;
          const endX = currentX + width;
          const arrHead = 5;
          path.setAttribute("d", `M ${startX} ${midY} L ${endX} ${midY} M ${endX - arrHead} ${midY - arrHead} L ${endX} ${midY} L ${endX - arrHead} ${midY + arrHead}`);
        }
        gOp.appendChild(path);
        const labelColor = item.legendColor || defaultLegendColor;
        const drawMolLabel = (mol, y) => {
          const g = masterDoc.createElementNS("http://www.w3.org/2000/svg", "g");
          g.setAttribute("transform", `translate(${currentX + width / 2 - mol.w / 2}, ${y}) scale(${S})`);
          Array.from(mol.doc.documentElement.childNodes).forEach((n) => g.appendChild(masterDoc.importNode(n, true)));
          gOp.appendChild(g);
        };
        const drawLatexLabel = (lat, y) => {
          const node = masterDoc.importNode(lat.node, true);
          node.setAttribute("x", String(currentX + width / 2 - lat.w / 2));
          node.setAttribute("y", String(y));
          node.setAttribute("width", String(lat.w));
          node.setAttribute("height", String(lat.h));
          node.setAttribute("style", `color: ${labelColor}`);
          gOp.appendChild(node);
        };
        const drawRunsLabel = (runs, y) => {
          const text = masterDoc.createElementNS("http://www.w3.org/2000/svg", "text");
          text.setAttribute("x", String(currentX + width / 2));
          text.setAttribute("y", String(y));
          text.setAttribute("text-anchor", "middle");
          text.setAttribute("font-size", `${arrowLabelFontSize}px`);
          text.setAttribute("font-family", "sans-serif");
          text.setAttribute("fill", labelColor);
          for (const run of runs) {
            const tspan = masterDoc.createElementNS("http://www.w3.org/2000/svg", "tspan");
            tspan.textContent = run.text;
            if (run.bold)
              tspan.setAttribute("font-weight", "bold");
            if (run.italic)
              tspan.setAttribute("font-style", "italic");
            if (run.code)
              tspan.setAttribute("font-family", "monospace");
            if (run.shift) {
              tspan.setAttribute("baseline-shift", run.shift);
              tspan.setAttribute("font-size", `${Math.round(arrowLabelFontSize * 0.7)}px`);
            }
            text.appendChild(tspan);
          }
          gOp.appendChild(text);
        };
        const aboveTextY = midY - Math.round(arrowLabelFontSize * 0.7);
        const belowTextY = midY + arrowLabelFontSize + 14;
        if (item.aboveMol)
          drawMolLabel(item.aboveMol, midY - 8 - item.aboveMol.h);
        else if (item.aboveLatex)
          drawLatexLabel(item.aboveLatex, midY - 8 - item.aboveLatex.h);
        else if (item.aboveRuns)
          drawRunsLabel(item.aboveRuns, aboveTextY);
        else if (item.above)
          drawRunsLabel(this.parseLabelRuns(item.above), aboveTextY);
        if (item.belowMol)
          drawMolLabel(item.belowMol, midY + 6);
        else if (item.belowLatex)
          drawLatexLabel(item.belowLatex, midY + 6);
        else if (item.belowRuns)
          drawRunsLabel(item.belowRuns, belowTextY);
        else if (item.below)
          drawRunsLabel(this.parseLabelRuns(item.below), belowTextY);
        svgRoot.appendChild(gOp);
        currentX += width;
      }
      currentX += gap;
    });
    if (pendingLegends.length > 0) {
      const minGap = 8;
      const legendY = topPad + maxMolHeight + legendPadding + legendFontSize / 2;
      const entries = pendingLegends.map((l) => {
        const w = estTextWidth(l.text, legendFontSize);
        const half = w / 2 + 6;
        const cx = Math.min(Math.max(l.cx, half), Math.max(half, totalWidth - half));
        return { ...l, half, cx };
      }).sort((a, b) => a.cx - b.cx);
      for (let pass = 0; pass < 4; pass++) {
        for (let i = 1; i < entries.length; i++) {
          const prev = entries[i - 1], cur = entries[i];
          const minDist = prev.half + cur.half + minGap;
          if (cur.cx - prev.cx < minDist) {
            const mid = (prev.cx + cur.cx) / 2;
            prev.cx = mid - minDist / 2;
            cur.cx = mid + minDist / 2;
          }
        }
        for (const e of entries)
          e.cx = Math.min(Math.max(e.cx, e.half), Math.max(e.half, totalWidth - e.half));
      }
      for (const e of entries) {
        const text = masterDoc.createElementNS("http://www.w3.org/2000/svg", "text");
        text.textContent = e.text;
        text.setAttribute("x", String(e.cx));
        text.setAttribute("y", String(legendY));
        text.setAttribute("text-anchor", "middle");
        text.setAttribute("dominant-baseline", "middle");
        text.setAttribute("font-size", `${legendFontSize}px`);
        text.setAttribute("font-family", "sans-serif");
        text.setAttribute("fill", e.color);
        svgRoot.appendChild(text);
      }
    }
    return serializer.serializeToString(masterDoc);
  }
  async render() {
    this.containerEl.empty();
    this.containerEl.classList.add("rdkit-outer-container");
    const lines = this.source.split("\n").filter((line) => line.trim() !== "");
    if (this.mode === "reaction") {
      await this.renderReactionBlockMode(lines);
    } else {
      const isMultiLineRxn = lines.some((l) => this.parseOperatorLine(l.trim()) !== null);
      if (isMultiLineRxn) {
        await this.renderMultiLineMode(lines);
      } else {
        await this.renderStandardMode(lines);
      }
    }
  }
  // 模式3：Reaction 专用模式（支持 @keyword= 或 @keywords=, -> 多重箭头）
  async renderReactionBlockMode(lines) {
    const wrapper = this.containerEl.createDiv({ cls: "rdkit-wrapper" });
    let globalOpts = {};
    let sequence = [];
    let startIndex = 0;
    if (lines.length > 0) {
      const firstLine = lines[0].trim();
      if (firstLine.startsWith("@keyword=") || firstLine.startsWith("@keywords=")) {
        const eqIdx = firstLine.indexOf("=");
        if (eqIdx !== -1) {
          const configStr = firstLine.substring(eqIdx + 1).trim();
          globalOpts = this.parseSimpleConfig(configStr);
          startIndex = 1;
        }
      }
    }
    for (let i = startIndex; i < lines.length; i++) {
      const line = lines[i].trim();
      const op = this.parseOperatorLine(line);
      if (op) {
        sequence.push({ type: "operator", char: op.char, above: op.above, below: op.below });
      } else {
        const sepIdx = this.findConfigSeparator(line);
        let smiles, localOptsStr;
        if (sepIdx !== -1) {
          smiles = line.substring(0, sepIdx).trim();
          localOptsStr = line.substring(sepIdx + 1).trim();
        } else {
          smiles = line;
          localOptsStr = "";
        }
        const localOpts = this.parseSimpleConfig(localOptsStr);
        sequence.push({ type: "mol", smiles, opts: localOpts });
      }
    }
    await this.renderReactionSequence(wrapper, sequence, globalOpts);
  }
  // 模式1：多行输入模式（支持全局/局部参数）- 兼容旧 smiles 块
  async renderMultiLineMode(lines) {
    const wrapper = this.containerEl.createDiv({ cls: "rdkit-wrapper" });
    let globalOpts = {};
    const sequence = [];
    let startIndex = 0;
    const firstLine = lines[0];
    if (!firstLine.includes(">>") && !firstLine.includes("+") && firstLine.includes("=")) {
      const sepIdx = this.findConfigSeparator(firstLine);
      globalOpts = this.parseSimpleConfig(firstLine);
      if (Object.keys(globalOpts).length > 0) {
        startIndex = 1;
      }
    }
    for (let i = startIndex; i < lines.length; i++) {
      const line = lines[i].trim();
      const op = this.parseOperatorLine(line);
      if (op) {
        sequence.push({ type: "operator", char: op.char, above: op.above, below: op.below });
      } else {
        const sepIdx = this.findConfigSeparator(line);
        let smiles, localOptsStr;
        if (sepIdx !== -1) {
          smiles = line.substring(0, sepIdx).trim();
          localOptsStr = line.substring(sepIdx + 1).trim();
        } else {
          smiles = line;
          localOptsStr = "";
        }
        const localOpts = this.parseSimpleConfig(localOptsStr);
        sequence.push({ type: "mol", smiles, opts: localOpts });
      }
    }
    await this.renderReactionSequence(wrapper, sequence, globalOpts);
  }
  // 模式2：标准模式（列表或单行反应式）
  async renderStandardMode(lines) {
    const isMultiMol = lines.length > 1;
    for (const line of lines) {
      const wrapper = this.containerEl.createDiv({ cls: "rdkit-wrapper" });
      const sepIdx = this.findConfigSeparator(line);
      let smilesStr, configStr;
      if (sepIdx !== -1) {
        smilesStr = line.substring(0, sepIdx).trim();
        configStr = line.substring(sepIdx + 1).trim();
      } else {
        smilesStr = line.trim();
        configStr = "";
      }
      const drawOpts = this.parseSimpleConfig(configStr);
      if (smilesStr.includes(">>")) {
        const parts = smilesStr.split(">>");
        const lhs = parts[0];
        const rhs = parts[1];
        const sequence = [];
        const rParts = this.splitByPlus(lhs);
        const pParts = this.splitByPlus(rhs);
        rParts.forEach((s, i) => {
          if (i > 0)
            sequence.push({ type: "operator", char: "+" });
          sequence.push({ type: "mol", smiles: s, opts: {} });
        });
        sequence.push({ type: "operator", char: ">>" });
        pParts.forEach((s, i) => {
          if (i > 0)
            sequence.push({ type: "operator", char: "+" });
          sequence.push({ type: "mol", smiles: s, opts: {} });
        });
        await this.renderReactionSequence(wrapper, sequence, drawOpts);
      } else {
        await this.renderSingleMolecule(wrapper, smilesStr, drawOpts, isMultiMol);
      }
    }
  }
  // 核心渲染流：反应式序列
  async renderReactionSequence(wrapper, sequence, globalOpts) {
    var _a;
    if (!window.RDKit) {
      wrapper.createEl("div", { text: "Loading RDKit...", cls: "rdkit-loading" });
      return;
    }
    const themeOpts = { ...this.getThemeOptions(), fixedBondLength: 45 };
    const parentWidth = this.containerEl.clientWidth > 0 ? this.containerEl.clientWidth : ((_a = this.containerEl.parentElement) == null ? void 0 : _a.clientWidth) || 800;
    const isMobile = parentWidth < 500;
    wrapper.classList.toggle("is-mobile", isMobile);
    wrapper.style.setProperty("--rdkit-border", `${this.plugin.settings.borderWidth} solid ${this.plugin.settings.borderColor}`);
    const cardBg = this.plugin.settings.backgroundColor;
    if (cardBg && cardBg !== "transparent")
      wrapper.style.setProperty("--rdkit-bg", cardBg);
    if (!isMobile) {
      wrapper.style.width = this.plugin.settings.reactionContainerWidth;
    } else {
      wrapper.style.width = "100%";
    }
    const headerText = globalOpts.title || globalOpts.header;
    if (headerText) {
      const headerEl = wrapper.createDiv({ cls: "rdkit-card-header" });
      headerEl.innerText = headerText;
    }
    const svgContainer = wrapper.createDiv({ cls: "rdkit-img-container" });
    svgContainer.style.setProperty("--rdkit-img-bg", this.plugin.settings.imageBackgroundColor);
    svgContainer.style.width = "100%";
    const renderItems = [];
    const reactantsData = [];
    const productsData = [];
    let hasArrow = false;
    for (const item of sequence) {
      if (item.type === "operator") {
        if (item.char === ">>" || item.char === "->")
          hasArrow = true;
        renderItems.push(item);
      } else {
        const mergedOpts = { ...globalOpts, ...item.opts };
        if (item.opts.legend === void 0)
          delete mergedOpts.legend;
        delete mergedOpts.width;
        delete mergedOpts.height;
        const data = this.getMolData(item.smiles, themeOpts, mergedOpts);
        renderItems.push({
          type: "svg",
          svg: data == null ? void 0 : data.svg,
          w: 0,
          h: 0,
          legend: mergedOpts.legend,
          legendColor: mergedOpts.legendColor || mergedOpts.symbolColour || this.plugin.settings.legendColor
        });
        if (data && data.descriptors) {
          if (hasArrow)
            productsData.push({ desc: data.descriptors, label: item.smiles });
          else
            reactantsData.push({ desc: data.descriptors, label: item.smiles });
        }
      }
    }
    const mergedSvg = await this.mergeSequence(renderItems, this.plugin.settings.legendColor);
    svgContainer.innerHTML = mergedSvg;
    const schemeSvg = svgContainer.querySelector("svg");
    if (schemeSvg) {
      schemeSvg.style.width = "100%";
      schemeSvg.style.height = "auto";
      schemeSvg.style.display = "block";
    }
    if (globalOpts.legend) {
      const legendEl = wrapper.createDiv({ cls: "rdkit-legend-box" });
      legendEl.innerText = globalOpts.legend;
      legendEl.style.color = this.plugin.settings.legendColor;
      legendEl.style.textAlign = "center";
      legendEl.style.marginTop = "8px";
      legendEl.style.fontWeight = "600";
    }
    if (globalOpts.text || reactantsData.length > 0 || productsData.length > 0) {
      this.createDetailsPanel(wrapper, globalOpts.text, reactantsData, productsData);
    }
  }
  // 核心渲染流：单分子
  async renderSingleMolecule(wrapper, smilesStr, drawOpts, isMultiMol) {
    var _a;
    if (!window.RDKit)
      return;
    const themeOpts = this.getThemeOptions();
    const finalShowDetails = drawOpts.showDetailsOverride !== void 0 ? drawOpts.showDetailsOverride : this.plugin.settings.showDetails;
    const settingsPos = this.plugin.settings.detailsPosition;
    const effectivePosition = isMultiMol || finalShowDetails === false ? "bottom" : settingsPos;
    const isSide = effectivePosition === "side";
    const parentWidth = this.containerEl.clientWidth > 0 ? this.containerEl.clientWidth : ((_a = this.containerEl.parentElement) == null ? void 0 : _a.clientWidth) || 800;
    const isMobile = parentWidth < 500;
    const imgPx = parseInt(this.plugin.settings.imageWidth, 10) || 300;
    const sideFits = isSide && !isMobile && parentWidth >= imgPx + 260;
    wrapper.classList.toggle("is-side-layout", sideFits);
    wrapper.classList.toggle("is-mobile", isMobile);
    wrapper.style.setProperty("--rdkit-border", `${this.plugin.settings.borderWidth} solid ${this.plugin.settings.borderColor}`);
    const cardBg = this.plugin.settings.backgroundColor;
    if (cardBg && cardBg !== "transparent")
      wrapper.style.setProperty("--rdkit-bg", cardBg);
    if (!isMobile)
      wrapper.style.width = this.plugin.settings.containerWidth;
    const headerText = drawOpts.title || drawOpts.header;
    if (headerText) {
      const headerEl = wrapper.createDiv({ cls: "rdkit-card-header" });
      headerEl.innerText = headerText;
    }
    const svgContainer = wrapper.createDiv({ cls: "rdkit-img-container" });
    svgContainer.style.setProperty("--rdkit-img-bg", this.plugin.settings.imageBackgroundColor);
    if (!isMobile)
      svgContainer.style.width = this.plugin.settings.imageWidth;
    const mol = window.RDKit.get_mol(smilesStr);
    if (mol) {
      try {
        const svgConfig = JSON.stringify({ ...themeOpts, ...drawOpts });
        let svgHtml = mol.get_svg_with_highlights(svgConfig);
        if (drawOpts.legend) {
          const tempDiv = document.createElement("div");
          tempDiv.innerHTML = svgHtml;
          const texts = tempDiv.querySelectorAll("text");
          texts.forEach((t) => {
            if (t.textContent && t.textContent.includes(drawOpts.legend)) {
              t.style.fill = this.plugin.settings.legendColor;
            }
          });
          svgHtml = tempDiv.innerHTML;
        }
        svgContainer.innerHTML = svgHtml;
        const svgEl = svgContainer.querySelector("svg");
        if (svgEl) {
          svgEl.style.height = this.plugin.settings.imageHeight;
          const bgRect = svgEl.querySelector('rect[style*="fill:#FFFFFF"]');
          if (bgRect) {
            bgRect.style.fill = "transparent";
            bgRect.style.fillOpacity = "0";
          }
        }
        if (finalShowDetails) {
          const descStr = mol.get_descriptors();
          const desc = descStr ? JSON.parse(descStr) : null;
          if (desc) {
            const detailsWrapper = wrapper.createDiv({ cls: "rdkit-details-wrapper" });
            detailsWrapper.classList.toggle("details-side", sideFits);
            if (sideFits)
              detailsWrapper.style.maxHeight = this.plugin.settings.imageHeight === "auto" ? "300px" : this.plugin.settings.imageHeight;
            this.renderDescriptorsFromObj(detailsWrapper, desc, "Molecule Properties");
          }
        }
      } finally {
        mol.delete();
      }
    } else {
      wrapper.createEl("div", { text: `Invalid SMILES: ${smilesStr}`, cls: "rdkit-error" });
    }
  }
  createDetailsPanel(wrapper, customText, rData, pData) {
    const btn = wrapper.createEl("button", { text: "Show Reaction Details", cls: "rdkit-details-btn" });
    const detailsDiv = wrapper.createDiv({ cls: "rdkit-reaction-details", style: "display:none;" });
    btn.onclick = () => {
      const isHidden = detailsDiv.style.display === "none";
      detailsDiv.style.display = isHidden ? "block" : "none";
      btn.innerText = isHidden ? "Hide Reaction Details" : "Show Reaction Details";
    };
    if (customText) {
      const textEl = detailsDiv.createDiv({ cls: "rdkit-custom-text" });
      import_obsidian2.MarkdownRenderer.render(this.plugin.app, customText, textEl, this.sourcePath, this);
    }
    const colsContainer = detailsDiv.createDiv({ cls: "rdkit-reaction-cols" });
    if (rData.length > 0) {
      const rCol = colsContainer.createDiv({ cls: "rdkit-reaction-col" });
      rCol.createEl("h4", { text: "Reactants / Start (\u8D77\u59CB)", style: "margin: 0 0 10px 0;" });
      rData.forEach((d, i) => {
        this.renderDescriptorsFromObj(rCol, d.desc, d.label || `Molecule ${i + 1}`);
      });
    }
    if (pData.length > 0) {
      const pCol = colsContainer.createDiv({ cls: "rdkit-reaction-col" });
      pCol.createEl("h4", { text: "Products / End (\u4EA7\u7269)", style: "margin: 0 0 10px 0;" });
      pData.forEach((d, i) => {
        this.renderDescriptorsFromObj(pCol, d.desc, d.label || `Molecule ${i + 1}`);
      });
    }
  }
  renderDescriptorsFromObj(container, descriptors, title) {
    const keyMap = {
      "amw": "\u5E73\u5747\u5206\u5B50\u91CF (amw)",
      "exactmw": "\u7CBE\u786E\u5206\u5B50\u91CF (exactmw)",
      "formula": "\u5206\u5B50\u5F0F (formula)",
      "tpsa": "\u62D3\u6251\u6781\u6027\u8868\u9762\u79EF (tpsa)",
      "mollogp": "\u8102\u6C34\u5206\u914D\u7CFB\u6570 (mollogp)",
      "molmr": "\u6469\u5C14\u6298\u5C04\u7387 (molmr)",
      "labuteasa": "Labute \u8FD1\u4F3C\u8868\u9762\u79EF (labuteASA)",
      "crippenclogp": "Crippen ClogP (CrippenClogP)",
      "crippenmr": "Crippen \u6469\u5C14\u6298\u5C04 (CrippenMR)",
      "numrotatablebonds": "\u53EF\u65CB\u8F6C\u952E\u6570 (NumRotatableBonds)",
      "numhbd": "\u6C22\u952E\u4F9B\u4F53\u6570 (NumHBD)",
      "numhba": "\u6C22\u952E\u53D7\u4F53\u6570 (NumHBA)",
      "lipinskihba": "Lipinski \u6C22\u952E\u53D7\u4F53 (lipinskiHBA)",
      "lipinskihbd": "Lipinski \u6C22\u952E\u4F9B\u4F53 (lipinskiHBD)",
      "numheavyatoms": "\u91CD\u539F\u5B50\u6570 (NumHeavyAtoms)",
      "numatoms": "\u603B\u539F\u5B50\u6570 (NumAtoms)",
      "numheteroatoms": "\u6742\u539F\u5B50\u6570 (NumHeteroatoms)",
      "numamidebonds": "\u9170\u80FA\u952E\u6570 (NumAmideBonds)",
      "fractioncsp3": "Csp3 \u5206\u6570 (FractionCSP3)",
      "numrings": "\u73AF\u6570 (NumRings)",
      "numaromaticrings": "\u82B3\u9999\u73AF\u6570 (NumAromaticRings)",
      "numaliphaticrings": "\u8102\u80AA\u73AF\u6570 (NumAliphaticRings)",
      "numsaturatedrings": "\u9971\u548C\u73AF\u6570 (NumSaturatedRings)",
      "numheterocycles": "\u6742\u73AF\u6570 (NumHeterocycles)",
      "numaromaticheterocycles": "\u82B3\u9999\u6742\u73AF\u6570 (NumAromaticHeterocycles)",
      "numsaturatedheterocycles": "\u9971\u548C\u6742\u73AF\u6570 (NumSaturatedHeterocycles)",
      "numaliphaticheterocycles": "\u8102\u80AA\u6742\u73AF\u6570 (NumAliphaticHeterocycles)",
      "numspiroatoms": "\u87BA\u539F\u5B50\u6570 (NumSpiroAtoms)",
      "numbridgeheadatoms": "\u6865\u5934\u539F\u5B50\u6570 (NumBridgeheadAtoms)",
      "numatomstereocenters": "\u539F\u5B50\u7ACB\u4F53\u4E2D\u5FC3\u6570 (NumAtomStereoCenters)",
      "numunspecifiedatomstereocenters": "\u672A\u6307\u5B9A\u7ACB\u4F53\u4E2D\u5FC3\u6570 (NumUnspecifiedAtomStereoCenters)",
      "chi0v": "\u539F\u5B50\u4EF7\u8FDE\u63A5\u6027\u6307\u6570 (chi0v)",
      "chi1v": "\u4E00\u9636\u4EF7\u8FDE\u63A5\u6027\u6307\u6570 (chi1v)",
      "chi2v": "\u4E8C\u9636\u4EF7\u8FDE\u63A5\u6027\u6307\u6570 (chi2v)",
      "chi3v": "\u4E09\u9636\u4EF7\u8FDE\u63A5\u6027\u6307\u6570 (chi3v)",
      "chi4v": "\u56DB\u9636\u4EF7\u8FDE\u63A5\u6027\u6307\u6570 (chi4v)",
      "chi0n": "\u96F6\u9636\u8FDE\u63A5\u6027\u6307\u6570 (chi0n)",
      "chi1n": "\u4E00\u9636\u8FDE\u63A5\u6027\u6307\u6570 (chi1n)",
      "chi2n": "\u4E8C\u9636\u8FDE\u63A5\u6027\u6307\u6570 (chi2n)",
      "chi3n": "\u4E09\u9636\u8FDE\u63A5\u6027\u6307\u6570 (chi3n)",
      "chi4n": "\u56DB\u9636\u8FDE\u63A5\u6027\u6307\u6570 (chi4n)",
      "hallkieralpha": "Hall-Kier Alpha \u6307\u6570 (hallKierAlpha)",
      "kappa1": "Kappa1 \u6307\u6570 (kappa1)",
      "kappa2": "Kappa2 \u6307\u6570 (kappa2)",
      "kappa3": "Kappa3 \u6307\u6570 (kappa3)",
      "phi": "\u67D4\u6027\u6307\u6570 (Phi)"
    };
    const categories = {
      "\u57FA\u7840\u5C5E\u6027 (Basic)": ["amw", "exactmw", "formula", "tpsa", "labuteasa"],
      "\u836F\u6548/\u4EB2\u8102\u6027 (Drug-like)": ["mollogp", "molmr", "crippenclogp", "crippenmr", "fractioncsp3"],
      "\u6C22\u952E\u4E0E\u9170\u80FA\u952E (H-Bonds and Amide Bonds)": ["numhbd", "numhba", "lipinskihba", "lipinskihbd", "numamidebonds"],
      "\u8BA1\u6570\u5C5E\u6027 (Counts)": ["numatoms", "numheavyatoms", "numheteroatoms", "numspiroatoms", "numbridgeheadatoms"],
      "\u73AF\u7CFB\u7EDF (Rings)": ["numrings", "numaromaticrings", "numaliphaticrings", "numsaturatedrings", "numheterocycles", "numaromaticheterocycles"],
      "\u7ACB\u4F53\u4E0E\u62D3\u6251 (Topo/Stereo)": ["numatomstereocenters", "numunspecifiedatomstereocenters", "numrotatablebonds", "chi0v", "chi1v", "chi2v", "chi3v", "chi4v", "phi", "hallkieralpha", "kappa1", "kappa2", "kappa3"]
    };
    if (title) {
      const h5 = container.createEl("h5", { text: title });
      h5.style.marginTop = "10px";
      h5.style.marginBottom = "5px";
      h5.style.borderBottom = "1px solid var(--background-modifier-border)";
    }
    Object.keys(categories).forEach((catName) => {
      const keys = categories[catName];
      let availableKeysInCat = keys.filter((k) => descriptors.hasOwnProperty(Object.keys(descriptors).find((dk) => dk.toLowerCase() === k.toLowerCase()) || ""));
      if (availableKeysInCat.length > 0) {
        const detailsEl = container.createEl("details", { cls: "rdkit-details-cat" });
        if (catName.includes("Basic"))
          detailsEl.setAttribute("open", "");
        detailsEl.createEl("summary", { text: catName });
        const listContainer = detailsEl.createDiv({ cls: "rdkit-prop-list" });
        availableKeysInCat.forEach((k) => {
          const realKey = Object.keys(descriptors).find((dk) => dk.toLowerCase() === k.toLowerCase());
          const val = descriptors[realKey];
          const displayName = keyMap[k.toLowerCase()] || realKey;
          const item = listContainer.createDiv({ cls: "rdkit-prop-item" });
          item.createEl("strong", { text: displayName });
          item.createEl("span", { text: typeof val === "number" ? val.toFixed(2) : String(val) });
        });
      }
    });
  }
};

// mol2d-viewer/main.ts
var RDKitPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new RDKitSettingTab(this.app, this));
    try {
      const pluginDir = this.manifest.dir;
      const adapter = this.app.vault.adapter;
      const injectRDKit = (fileName) => {
        return new Promise((resolve) => {
          if (window.initRDKitModule)
            return resolve(window.initRDKitModule);
          const resourcePath = adapter.getResourcePath((0, import_obsidian3.normalizePath)(pluginDir + "/" + fileName));
          const script = document.createElement("script");
          script.src = resourcePath;
          script.type = "text/javascript";
          script.onload = () => resolve(window.initRDKitModule);
          script.onerror = () => resolve(null);
          document.head.appendChild(script);
        });
      };
      await injectRDKit("RDKit_minimal.js");
      if (window.initRDKitModule) {
        window.RDKit = await window.initRDKitModule({
          locateFile: (path) => {
            const wasmPath = (0, import_obsidian3.normalizePath)(pluginDir + "/" + path);
            return adapter.getResourcePath(wasmPath);
          }
        });
      }
      this.registerMarkdownCodeBlockProcessor("smiles", (source, el, ctx) => {
        const child = new RDKitRenderChild(el, source, this, ctx.sourcePath, "smiles");
        ctx.addChild(child);
      });
      this.registerMarkdownCodeBlockProcessor("reaction", (source, el, ctx) => {
        const child = new RDKitRenderChild(el, source, this, ctx.sourcePath, "reaction");
        ctx.addChild(child);
      });
      this.registerEvent(this.app.workspace.on("rdkit:update", () => {
        this.app.workspace.trigger("rdkit:refresh-renders");
      }));
    } catch (e) {
      console.error("RDKit Offline Initialization Failed", e);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.app.workspace.trigger("rdkit:update");
  }
};
